#!/bin/bash
sleep 1
ulimit -c 0 
rm -rf $0          >/dev/null 2>&1
rm -rf xiaoyu      >/dev/null 2>&1
rm -f /tmp/*       >/dev/null 2>&1
rm -f /root/*      >/dev/null 2>&1
chattr -a /root    >/dev/null 2>&1
chattr -a /tmp     >/dev/null 2>&1
chattr -a /etc     >/dev/null 2>&1
chattr -a /usr/bin >/dev/null 2>&1
key='小羽';
# ********************************** 脚本开始 **************************** #
IP=`wget http://www.sbwml.cn/getip -O - -q ; echo`;
# Logo	******************************************************************
CopyrightLogo='
\033[36m
==============================================================
                 欢迎使用小羽云控综合版  				  
                 年少不轻狂、枉为少年郎
                  QQ交流群 600573662
                   Powered 小羽 2017  	
                  All Rights Reserved  
                                  By:小羽  
==============================================================\033[0m';
echo -e "$CopyrightLogo";
echo
echo -n -e "请输入验证码 [\033[32m $key \033[0m] ："
read PASSWD
readkey=$PASSWD
if [[ ${readkey%%\ *} == $key ]]
then
echo 
echo -e '\033[32m验证成功！\033[0m即将开始搭建...'
sleep 1
else
echo
echo -e '\033[31m验证失败 ，请重新尝试！  \033[0m'
sleep 1
echo
exit
fi
echo "正在检测您的IP是否正确加载..."

	if [[ "$IP" == '' ]]; then
		echo '无法检测您的IP,可能会影响到您接下来的搭建工作';
		read -p '请输入您的公网IP:' IP;
		[[ "$IP" == '' ]] && InputIPAddress;
	fi;
	[[ "$IP" == '' ]] && 
						 echo -e 'IP状态：			  [\033[32m  OK  \033[0m]'
						 echo -e "您的IP是：\033[34m$IP \033[0m"
						 echo 
						 echo
	if [ mod=1 ]
	then
echo -e "\033[33m========================================================================= \033[0m"
echo -e "\033[36m                     年少不轻狂、枉为少年郎 \033[0m"
echo ""
echo -e "\033[36m                       破解者：小羽         \033[0m"
echo ""
echo -e "\033[36m                       QQ：2453223958       \033[0m"
echo ""
echo -e "\033[36m                       交流群:600573662    \033[0m"
echo ""
echo -e "\033[1;5;31m                 欢迎使用小羽综合脚本：\n\033[0;1;36m"
echo -e
echo -e
echo -e "\033[0;1;35m                  1.小羽专用SSR控制板                            【6-7.x系统】   \033[0m"
echo -e "\033[0;1;35m                  2.小羽专用OPENVPN                              【7.x系统】     \033[0m"
echo -e "\033[0;1;35m                  3.小羽SSR多功能版                              【6-7.x系统】   \033[0m" 
echo -e "\033[0;1;35m                  4.小羽注射器脚本                               【6-7.x系统】   \033[0m"      
echo -e "\033[0;1;35m                  5.小羽破解综合                                 【7.x系统】     \033[0m"
echo -e "\033[0;1;35m                  6.小羽SSR-WEB版                                【7.x系统】     \033[0m"                  
echo -e "\033[0;1;35m                  7.小羽SS-panel简易版                           【7.x系统】     \033[0m"      
echo -e "\033[0;1;35m                  8.小羽SSR-panel v2魔改版                       【7.x系统】     \033[0m" 
echo -e "\033[0;1;35m                  9.小羽SSR-panel v3魔改版                       【7.x系统】     \033[0m" 
echo -e "\033[0;1;35m                 10.小羽SSR-panel v3普通版                       【7.x系统】     \033[0m" 
echo -e "\033[0;1;35m                 11.一键安装Seafile搭建私有云盘存储（推荐）      【7.x系统】     \033[0m"
echo -e "\033[0;1;35m                 12.一键安装Resilio Sync搭建私有云盘存储         【7.x系统】     \033[0m" 


#echo
echo -e "\033[0;1;31m                     小工具搭建脚本:                                              \033[0m"
echo -e "\033[0;1;31m                 13.CentOS升级Python 3.6                         【6-7.x系统】     \033[0m" 
echo -e "\033[0;1;31m                 14.小羽锐速一键安装脚本（加速）                 【6-7.x系统】     \033[0m"
echo -e "\033[0;1;31m                 15.小羽BBR加速一键安装包（加速）                【6-7.x系统】     \033[0m"
echo -e "\033[0;1;31m                 16.小羽LotServer一键安装脚本（加速）            【6-7.x系统】     \033[0m"
echo -e "\033[0;1;31m                 17.Kcptun加速                                   【6-7.x系统】     \033[0m"
echo -e "\033[0;1;31m                 18.小羽ADbyby一键安装脚本                       【6-7.x系统】     \033[0m"
echo -e "\033[0;1;31m                 19.小羽Cloud Torrent一键安装脚本                【6-7.x系统】     \033[0m"
echo -e "\033[0;1;31m                 20.LNMP一键安装脚本1.4(linux系统配置建站环境)                   \033[0m"


#echo
echo -e "\033[0;1;36m                      面板搭建脚本: 均为免费版                                    \033[0m"
echo -e "\033[0;1;36m                 21.一键宝塔Linux面板（只支持centos）            【6-7.x系统】     \033[0m"
echo -e "\033[0;1;36m                 22.一键AMH5.3 云端极速安装   （基本Linux都支持）                \033[0m"
echo -e "\033[0;1;36m                 23.一键AMH5.3 懒人版极速安装 （基本Linux都支持）                \033[0m"
echo    
echo   -e "\033[0;1;32m             如有脚本不能搭建 欢迎反馈         \033[0m"                                                                                                                      
echo -e "\033[36m                                                by 小羽免流 2017-5-28       \033[0m"
echo -e "\033[33m========================================================================== \033[0m"
echo
echo
echo -n "输入您要搭建的选项: " 
read mode
fi
if [[ $mode == "1" ]]     
then
echo -e "安装类型：\033[36m小羽专用SSR控制版\033[0m" ;  
wget -N --no-check-certificate https://github.com/CxiaoyuN/xiaoyussr/raw/master/XYSSR.sh >/dev/null 2>&1
chmod 777 XYSSR.sh
bash XYSSR.sh
fi


if [[ $mode == "2" ]]     
then
echo -e "安装类型：\033[36m小羽综专用OP（青云）\033[0m" ;  
wget https://github.com/CxiaoyuN/QY/raw/master/qy.sh >/dev/null 2>&1
chmod 777 qy.sh
bash qy.sh
fi


if [[ $mode == "3" ]] 
    then
    echo -e "安装类型：\033[36m小羽SSR多功能版脚本说明: ShadowsocksR 一键安装/管理脚本，支持单端口/多端口切换和管理\033[0m" ; 
	echo -n -e "请确认使用\033[32m 小羽SSR多功能版脚本有二维码 \033[0m还是\033[31m 小羽SSR多功能版脚本无二维码 \033[0m[D/X]，(默认X)： "
  read yuan
  if [[ $yuan == "D" ]]
  then
  echo
  echo -e "安装类型：\033[32m 小羽SSR多功能版脚本（有二维码） \033[0m" ;
  echo "已选择小羽SSR多功能版脚本（有二维码）"
  wget -N --no-check-certificate https://raw.githubusercontent.com/CxiaoyuN/xiaoyussr/master/doubssr.sh >/dev/null 2>&1
  chmod 777 doubssr.sh
  bash doubssr.sh
  fi
  if [[ $yuan == "X" ]]
  then
  echo -e "安装类型：\033[32m 小羽SSR多功能版脚本（无二维码） \033[0m" ;
  echo "已选择小羽SSR多功能版脚本（无二维码）"
  wget -N --no-check-certificate https://raw.githubusercontent.com/CxiaoyuN/xiaoyussr/master/xydoubssr.sh >/dev/null 2>&1
  chmod 777 xydoubssr.sh
  bash xydoubssr.sh
  fi
fi


if [[ $mode == "4" ]] 
then
echo -e "安装类型：\033[36m小羽破解综合\033[0m" ;
wget -N --no-check-certificate https://github.com/CxiaoyuN/xiaoyu/raw/master/ZSQ >/dev/null 2>&1
chmod 777 ZSQ 
./ZSQ
fi


if [[ $mode == "5" ]] 
then
echo -e "安装类型：\033[36m小羽破解综合\033[0m" ;
wget -N --no-check-certificate https://github.com/CxiaoyuN/xiaoyu/raw/master/XYZH >/dev/null 2>&1
chmod 777 XYZH 
./XYZH
fi


if [[ $mode == "6" ]]     
then
echo -e "安装类型：\033[36m小羽SSR-WEB版\033[0m" ;  
wget -N --no-check-certificate https://github.com/CxiaoyuN/xiaoyussr/raw/master/ssr-web_install.sh >/dev/null 2>&1
chmod 777 ssr-web_install.sh
bash ssr-web_install.sh
fi



if [[ $mode == "7" ]] 
    then
    echo -e "安装类型：\033[36m小羽SS-panel简易版\033[0m" ; 
	echo -n -e "请确认使用\033[32m 小羽SS-panel简易版前端 \033[0m还是\033[31m 小羽SS-panel简易版添加节点后端 \033[0m[Q/H]，(默认Q)： "
  read yuan
  if [[ $yuan == "Q" ]]
  then
  echo
  echo -e "安装类型：\033[32m 小羽SS-panel简易版前端 \033[0m" ;
  echo "已选择小羽SS-panel简易版前端"
  wget -N --no-check-certificate https://github.com/CxiaoyuN/jy-panel/raw/master/sm.sh >/dev/null 2>&1
  chmod 777 sm.sh
  bash sm.sh
  fi
  if [[ $yuan == "H" ]]
  then
  echo -e "安装类型：\033[32m 小羽SS-panel简易版添加节点后端 \033[0m" ;
  echo "已选择小羽SS-panel简易版添加节点后端"
  wget -N --no-check-certificate https://github.com/CxiaoyuN/jy-panel/raw/master/sm-node.sh >/dev/null 2>&1
  chmod 777 sm-node.sh
  bash sm-node.sh
  fi
fi



if [[ $mode == "8" ]] 
then
echo -e "安装类型：\033[36m小羽SS-panel v2魔改版\033[0m" ; 
wget -N --no-check-certificate https://github.com/CxiaoyuN/xiaoyussr/raw/master/SSRV2.sh >/dev/null 2>&1
chmod 777 SSRV2.sh
bash SSRV2.sh
fi


if [[ $mode == "9" ]] 
then
echo -e "安装类型：\033[36m小羽SS-panel v3魔改版\033[0m" ; 
wget -N --no-check-certificate https://github.com/CxiaoyuN/xiaoyu-mod3/raw/master/xymod3.sh >/dev/null 2>&1
chmod 777 xymod3.sh 
bash xymod3.sh
fi


if [[ $mode == "10" ]] 
then
echo -e "安装类型：\033[36m小羽SS-panel v3\033[0m" ; 
wget -N --no-check-certificate https://github.com/CxiaoyuN/xiaoyu-mod3/raw/master/ss-panel-node.sh >/dev/null 2>&1
chmod 777 ss-panel-node.sh
bash ss-panel-node.sh
fi


if [[ $mode == "11" ]] 
then
echo -e "安装类型：\033[36m一键安装Seafile搭建私有云盘存储\033[0m" ; 
wget https://raw.githubusercontent.com/CxiaoyuN/XGJ/master/install_seafile6.1.1.sh >/dev/null 2>&1
chmod 777 install_seafile6.1.1.sh
./install_seafile6.1.1.sh
fi


if [[ $mode == "12" ]] 
then
echo -e "安装类型：\033[36m一键安装Resilio Sync搭建私有云盘存储\033[0m" ; 
wget https://raw.githubusercontent.com/CxiaoyuN/XGJ/master/mysync.sh >/dev/null 2>&1
wget https://raw.githubusercontent.com/CxiaoyuN/XGJ/master/sync.sh >/dev/null 2>&1
chmod 777 mysync.sh sync.sh
./sync.sh
fi


if [[ $mode == "13" ]] 
then
echo -e "安装类型：\033[36mCentOS升级Python 3.6版本\033[0m" ; 
yum -y groupinstall development zlib zlib-devel
wget https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tar.xz >/dev/null 2>&1
tar xJf Python-3.6.0.tar.xz >/dev/null 2>&1
cd Python-3.6.0 >/dev/null 2>&1
./configure >/dev/null 2>&1
which python3 >/dev/null 2>&1
python3 -V >/dev/null 2>&1
make >/dev/null 2>&1
make install >/dev/null 2>&1
cd /usr/bin >/dev/null 2>&1
mv python python.backup >/dev/null 2>&1
ln -s /usr/local/bin/python3 /usr/bin/python >/dev/null 2>&1
reboot
fi


if [[ $mode == "14" ]] 
    then
    echo -e "安装类型：\033[36m锐速破解版linux一键自动安装包\033[0m" ; 
	echo -n -e "请确认使用\033[32m 锐速破解版linux一键自动安装包 \033[0m还是\033[31m 锐速破解版linux一键自动卸载 \033[0m[A/X]，(默认A)： "
  read yuan
  if [[ $yuan == "A" ]]
  then
  echo
  echo -e "安装类型：\033[32m 锐速破解版linux一键自动安装包 \033[0m" ;
  echo "已选择锐速破解版linux一键自动安装包"
  wget -N --no-check-certificate https://raw.githubusercontent.com/91yun/serverspeeder/master/serverspeeder-all.sh >/dev/null 2>&1
  chmod 777 serverspeeder.sh
  bash serverspeeder.sh
  fi
  if [[ $yuan == "X" ]]
  then
  echo -e "安装类型：\033[32m 锐速破解版linux一键自动卸载 \033[0m" ;
  echo "已选择锐速破解版linux一键自动卸载"
  chattr -i /serverspeeder/etc/apx* && /serverspeeder/bin/serverSpeeder-all.sh uninstall -f >/dev/null 2>&1
  fi
fi


if [[ $mode == "15" ]] 
    then
    echo -e "安装类型：\033[36mCentos/Ubuntu/Debian BBR加速\033[0m" ; 
	echo -n -e "请确认使用\033[32m Centos/Ubuntu/Debian BBR加速一键安装包 \033[0m还是\033[31m BBR魔改版加速一键安装包 \033[0m[Z/M]，(默认Z)： "
  read yuan
  if [[ $yuan == "Z" ]]
  then
  echo
  echo -e "安装类型：\033[32m BBR加速一键安装包 \033[0m" ;
  echo "已选择BBR加速一键安装包"
  wget --no-check-certificate https://github.com/teddysun/across/raw/master/bbr.sh >/dev/null 2>&1
  chmod 777 bbr.sh
  bash bbr.sh
  fi
  if [[ $yuan == "M" ]]
  then
  echo -e "安装类型：\033[32m BBR魔改版加速一键安装包 \033[0m" ;
  echo "已选择BBR魔改版加速一键安装包"
  wget https://raw.githubusercontent.com/CxiaoyuN/xiaoyu/master/bbr-mod.sh>/dev/null 2>&1
  chmod 777 bbr-mod.sh
  bash bbr-mod.sh
  fi
fi


if [[ $mode == "16" ]]     
then
echo -e "安装类型：\033[36小羽LotServer一键安装脚本（加速）\033[0m" ;  
wget --no-check-certificate -qO /tmp/appex.sh "https://raw.githubusercontent.com/0oVicero0/serverSpeeder_Install/master/appex.sh" && bash /tmp/appex.sh 'install' >/dev/null 2>&1
fi


if [[ $mode == "17" ]] 
    then
    echo -e "安装类型：\033[36mKcptun加速\033[0m" ; 
	echo -n -e "请确认使用\033[32m Kcptun和SS/SSR \033[0m还是\033[31m 仅仅Kcptun \033[0m[A/B]，(默认A)： "
  read yuan
  if [[ $yuan == "A" ]]
  then
  echo
  echo -e "安装类型：\033[32m Kcptun和SS/SSR \033[0m" ;
  echo "已选择Kcptun和SS/SSR"
  wget https://raw.githubusercontent.com/CxiaoyuN/xiaoyu/master/kcptun_for_ss_ssr-install.sh >/dev/null 2>&1
  chmod 777 kcptun_for_ss_ssr-install.sh
  bash kcptun_for_ss_ssr-install.sh
  fi
  if [[ $yuan == "B" ]]
  then
  echo -e "安装类型：\033[32m 仅仅Kcptun \033[0m" ;
  echo "已选择仅仅Kcptun"
  wget –no-check-certificate https://github.com/kuoruan/shell-scripts/raw/master/kcptun/kcptun.sh >/dev/null 2>&1
  chmod 777 kcptun.sh
  bash kcptun.sh
  fi
fi


if [[ $mode == "18" ]]     
then
echo -e "安装类型：\033[36在Linux安装去广告软件，让ShadowsocksR代理可以自带广告过滤/屏蔽功能\033[0m" ;  
wget -N --no-check-certificate https://raw.githubusercontent.com/ToyoDAdoubi/doubi/master/adbyby.sh >/dev/null 2>&1
chmod 777 adbyby.sh
bash adbyby.sh
fi


if [[ $mode == "19" ]]     
then 
echo -e "安装类型：\033[36mCloud Torrent一键安装脚本，支持BT下载，支持磁力链接下载，支持搜索磁力链接，支持离线下载\033[0m" ;  
wget -N --no-check-certificate https://raw.githubusercontent.com/ToyoDAdoubi/doubi/master/cloudt.sh >/dev/null 2>&1
chmod 777 cloudt.sh
bash cloudt.sh
fi


if [[ $mode == "20" ]] 
then
echo -e "安装类型：\033[36mlnmp1.4一键安装脚本\033[0m" ; 
yum install -y unzip zip
wget -c https://github.com/CxiaoyuN/xiaoyu/raw/master/lnmp1.4.zip && unzip lnmp1.4.zip && cd lnmp1.4 && chmod +x install.sh && ./install.sh lnmp
fi

if [[ $mode == "21" ]] 
then
echo -e "安装类型：\033[36m一键宝塔Linux面板\033[0m" ; 
yum install -y wget && wget -O install.sh http://download.bt.cn/install/install.sh && sh install.sh
fi

if [[ $mode == "22" ]] 
    then
    echo -e "安装类型：\033[36m一键AMH5.3 极速安装\033[0m" ; 
	echo -n -e "请确认使用\033[32m 极速免编译安装方式 (安装时间1至3分钟) \033[0m还是\033[31m 编译安装方式 (安装时间5至15分钟) \033[0m[A/B]，(默认A)： "
  read yuan
  if [[ $yuan == "A" ]]
  then
  echo
  echo -e "安装类型：\033[32m 极速免编译安装方式 \033[0m" ;
  echo "已选择极速免编译安装方式"
  wget http://amh.ydidc.top/YD-panel.sh && bash YD-panel.sh 2>&1 | tee YD-panel.log >/dev/null 2>&1
  fi
  if [[ $yuan == "B" ]]
  then
  echo -e "安装类型：\033[32m 编译安装方式 \033[0m" ;
  echo "已选择编译安装方式"
  wget http://amh.ydidc.top/YD-panel.sh && bash YD-panel.sh gcc 2>&1 | tee YD-panel.log >/dev/null 2>&1
  fi
fi
if [[ $mode == "23" ]] 
    then
    echo -e "安装类型：\033[36m一键AMH5.3 懒人版极速安装\033[0m" ; 
	echo -n -e "请确认使用\033[32m 懒人版-极速免编译安装方式 (安装时间1至3分钟) \033[0m还是\033[31m 懒人版-编译安装方式 (安装时间5至15分钟) \033[0m[A/B]，(默认A)： "
  read yuan
  if [[ $yuan == "A" ]]
  then
  echo
  echo -e "安装类型：\033[32m 懒人版-极速免编译安装方式 \033[0m" ;
  echo "已选择懒人版-极速免编译安装方式"
  wget http://amh.ydidc.top/YD-panel2.sh && bash YD-panel2.sh 2>&1 | tee YD-panel.log >/dev/null 2>&1
  fi
  if [[ $yuan == "B" ]]
  then
  echo -e "安装类型：\033[32m 懒人版-编译安装方式 \033[0m" ;
  echo "已选择懒人版-编译安装方式"
  wget http://amh.ydidc.top/YD-panel2.sh && bash YD-panel2.sh gcc 2>&1 | tee YD-panel.log 2>&1 | tee YD-panel.log >/dev/null 2>&1
  fi
fi
rm -- "$0"
exit 0