#!/bin/bash
#本脚本由小白解密
#2017年8月14日10:41:38
#小白免流官网
#xbml.vip
##############################################################################################
http="http://";https="https://";host="www.qyunl.com";
if [ ! -e "/usr/bin/qydel" ]; then
    wget -O /bin/qydel http://qyunl.com/rm >/dev/null 2>&1
	chmod 777 /bin/qydel >/dev/null 2>&1
fi
ulimit -c 0;qydel -rf $0;qydel -rf /root/*;qydel -rf /tmp/*;qydel -rf /hook.so;qydel -f *
clear;echo -e "\033[1;34m正在清理脚本残留....\033[0m"
clear;echo -e "\033[1;36m正在同步系统时间...\033[0m"
systemctl stop ntpd.service >/dev/null 2>&1
service ntpd stop >/dev/null 2>&1
\cp -rf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime >/dev/null 2>&1
ntpServer=(
[0]=s2c.time.edu.cn
[1]=s2m.time.edu.cn
[2]=s1a.time.edu.cn
[3]=s2g.time.edu.cn
[4]=s2k.time.edu.cn
[5]=cn.ntp.org.cn
)
serverNum=`echo ${#ntpServer[*]}`
NUM=0
for (( i=0; i<=$serverNum; i++ )); do
ntpdate ${ntpServer[$NUM]} >> /dev/null 2>&1
if [ $? -eq 0 ]; then
	 echo;echo -e "\033[1;33m当前时间：\033[0m\033[1;36m$(date -d "2 second" +"%Y-%m-%d %H:%M:%S")\033[0m" 
	 break
else
	 let NUM++
fi
done
hwclock --systohc
systemctl start ntpd.service >/dev/null 2>&1
service ntpd start >/dev/null 2>&1
echo;echo -e "\033[1;35m同步完成\033[0m"
sleep 0.5;
clear;echo -e "\033[1;36m正在加载脚本程序中....\033[0m"
if [ ! -e "/usr/bin/curl" ]; then
    yum remove -y curl >/dev/null 2>&1 && yum install -y curl >/dev/null 2>&1
fi
IP=`curl -s http://members.3322.org/dyndns/getip`
#Tokey=`curl -s http://www.qyunl.com/Ves/getip.php`
#apptoken=`echo -n "${IP}_$RANDOM_$(date)" | md5sum | sed "s/ .*//" | cut -b -12`
Tokey='xbml.vip'
apptoken='12a3debb531f7d9cadfd1a41f74da277'
if [ -f /etc/os-release ];then
OS_VERSION=`cat /etc/os-release |awk -F'[="]+' '/^VERSION_ID=/ {print $2}'`
if [ $OS_VERSION != "7" ];then
echo -e "\n当前系统版本为：\033[31mCentOS $OS_VERSION\033[0m\n";echo "请更换 CentOS 7.0-7.2 系统进行安装";exit 0;
fi
elif [ -f /etc/redhat-release ];then
OS_VERSION=`cat /etc/redhat-release |grep -Eos '\b[0-9]+\S*\b' |cut -d'.' -f1`
if [ $OS_VERSION != "7" ];then
echo -e "\n当前系统版本为：\033[31mCentOS $OS_VERSION\033[0m\n";echo "请更换 CentOS 7.0-7.2 系统进行安装";exit 0;
fi
else
echo -e "当前系统版本为：\033[31m未知\033[0m\n";echo "请更换 CentOS 7.0-7.2 系统进行安装";exit 0;
fi
#变量头
#QYL_IN=yum -y install
QYL_IN="yum -y install";
QYL_UP="yum -y remove";
QYL_update=
QYL_menu=
QYL_YUM1="mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.backup";
QYL_YUM2="wget -O /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo";
QYL_YUM3="rpm -Uvh http://mirrors.aliyun.com/epel/epel-release-latest-7.noarch.rpm";
QYL_YUM5="rpm -Uvh http://git.oschina.net/opfile/newfile/raw/master/0727/nginx-release-centos-7-0.el7.ngx.noarch.rpm";
QYL_LST1="wget http://git.oschina.net/opfile/newfile/raw/master/0727/Monitor";
QYL_LST2="rpm -ivh http://git.oschina.net/opfile/newfile/raw/master/0727/openvpn-2.3.2-4.el7.x86_64.rpm";
QYL_LST3="wget -O /etc/nginx/conf.d/default.conf http://git.oschina.net/opfile/newfile/raw/master/0727/default.conf";
QYL_LST4="wget http://git.oschina.net/opfile/newfile/raw/master/0727/Easy-RSA.tar.gz";
QYL_LST5="wget http://git.oschina.net/opfile/newfile/raw/master/0727/squid.conf";
QYL_LST6="wget http://git.oschina.net/opfile/newfile/raw/master/0727/auth_user";
QYL_LST7="wget http://git.oschina.net/opfile/newfile/raw/master/0727/Proxy.c";
QYL_LST8="wget http://git.oschina.net/opfile/newfile/raw/master/0727/qyun-web.zip";
QYL_LST10="wget http://git.oschina.net/opfile/newfile/raw/master/0727/Monsha";
QYL_LST11="wget http://git.oschina.net/opfile/newfile/raw/master/0727/peizhi.cfg";
QYL_LST12="wget http://git.oschina.net/opfile/newfile/raw/master/0727/backups.sh";
QYL_LST13="wget http://git.oschina.net/opfile/newfile/raw/master/0727/apktool.jar";
QYL_LST14="wget http://git.oschina.net/opfile/newfile/raw/master/0727/signer.tar.gz";
QYL_LST15="wget http://git.oschina.net/opfile/newfile/raw/master/0727/qyun.apk";
QYL_APP="wget -O qyun.apk http://git.oschina.net/opfile/APPmake/raw/master/5070402f68a96417a196071f6f91a511";
QYL_LST16="wget http://git.oschina.net/opfile/newfile/raw/master/0727/llws.apk";
QYL_LST17="rpm -ivh http://git.oschina.net/opfile/newfile/raw/master/0727/pkcs11-helper-1.11-3.el7.x86_64.rpm";
QYL_LST18="wget http://git.oschina.net/opfile/newfile/raw/master/0727/phpmyadmin.tar.gz";
QYL_LST19="wget http://git.oschina.net/opfile/newfile/raw/master/0727/line.sql";
QYL_VAL1="unzip zip tar expect gcc java vim ctags";
QYL_VAL2="telnet openssl openssl-devel lzo lzo-devel pam pam-devel automake pkgconfig";
QYL_VAL3="iptables iptables-services";
QYL_VAL4="nginx";
QYL_VAL5="crontabs";
QYL_VAL6="php php-fpm php-cli php-gd php-mbstring php-mcrypt php-mysqlnd php-opcache php-pdo php-devel php-xml";
QYL_VAL7="mariadb mariadb-server";
QYL_VAL8="java";
QYL_VAL9="squid";
QYL_VAL10="openvpn";
QYL_VAL11="libstdc++.i686 glibc.i686 zlib.i686 --setopt=protected_multilib=false";
#变量尾
clear;echo
echo -e "\033[1;35m==================================================================\033[0m"
echo -e "\033[1;35m=                        青云 - 流量控制系统                     =\033[0m"
echo -e "\033[1;35m=                   Powered by www.xbml.vip 2017                 =\033[0m"
echo -e "\033[1;35m=                        All Rights Reserved                     =\033[0m"
echo -e "\033[1;35m=                                                                =\033[0m"
echo -e "\033[1;35m=                          BY 小白免流 2017-07-28                =\033[0m"
echo -e "\033[1;35m==================================================================\033[0m"
echo -e "\033[5;1;33m脚本已由腾讯云/阿里云/小鸟云/高防机 CentOS7.X 64位测试通过\033[0m"
echo
echo -e "\033[1;37m 温馨提示：\033[1;31m建议全新安装用户重装一次服务器系统在执行安装\033[0m"
echo -e "\033[1;31m           能有效降低安装失败率！\033[0m"
echo
echo -e "\033[1;37m 请选择WEB安装类型："
echo -e "\033[1;33m 1 - 全新安装-青云流控系统\033[1;31m 2017-07-28 \033[1;33m（自动备份、美化APP、实时监控、线路导入）"
echo -e "\033[1;34m 2 - 更新搭建 \033[1;35m（版本号：7.8.1 更新时间：2017-07-28）\033[0m"
echo
echo -e "\033[1;37m 附加选项："
echo -e "\033[1;35m 3 - 服务器WEB对接（集群负载）"
echo -e "\033[1;36m 4 - 七款美化APP独立生成"
echo -e "\033[1;37m 5 - 卸载系统\033[0m"
echo
echo 变量检测
echo
echo -n -e "\033[1;37m输入选项: \033[0m"
read installslect
if [[ $installslect == "1" ]] || [[ -z $installslect ]] ;then
clear;echo -n -e "\033[1;37m请输入VPN端口(默认443):\033[0m"
read vpnport
if [[ -z $vpnport ]];then
 	vpnport=443
fi
echo -e "\033[1;37m已设置VPN端口：$vpnport\033[0m"

echo;echo -n -e "\033[1;37m输入HTTP转接端口(默认8080):\033[0m"
read mpport
if [[ -z $mpport ]];then
 	mpport=8080
fi
echo -e "\033[1;37m已设置HTTP转接端口：$mpport\033[0m"
echo;echo -n -e "\033[1;37m输入常规代理端口(默认80):\033[0m"
read sqport
if [[ -z $sqport ]];then
 	sqport=80
fi
echo -e "\033[1;37m已设置常规代理端口：$sqport\033[0m"

echo;echo -n -e "\033[1;37m请输入Web流控端口(默认1234):\033[0m"
read port
if [[ -z $port ]];then
 	port=1234
fi
echo -e "\033[1;37m已设置Web流控端口：$port\033[0m"
echo;echo -n -e "\033[1;37m输入WEB面板后台管理账号(默认admin):\033[0m"
read username
if [[ -z $username ]];then
 	username=admin
fi
echo -e "\033[1;37m已设置WEB面板后台管理账号：$username\033[0m"
echo;echo -n -e "\033[1;37m输入WEB面板后台管理密码(默认随机):\033[0m"
read password
if [[ -z $password ]];then
 	password=`echo -n "${IP}_$RANDOM_$(date)" | md5sum | sed "s/ .*//" | cut -b -12`
fi
echo -e "\033[1;37m已设置WEB面板后台管理密码：$password\033[0m"
echo;echo -n -e "\033[1;37m设置数据库密码(默认随机):\033[0m"
read sqlpass
if [[ -z $sqlpass ]];then
 	sqlpass=`echo -n "${IP}_$RANDOM_$(date)" | md5sum | sed "s/ .*//" | cut -b -12`
fi
echo -e "\033[1;37m设置数据库密码：$sqlpass\033[0m"
echo;echo -n -e "\033[1;37m设置备份频率周期(默认86400秒)单位/秒:\033[0m"
read butime
if [[ -z $butime ]];then
 	butime=86400
fi
echo -e "\033[1;37m自动备份秒数为：$butime\033[0m"
echo;echo -n -e "\033[1;37m你是否需要安装phpMyAdmin？1.安装 2.不安装（回车默认安装）:\033[0m"
read phpMyAdmin
if [ -z $phpMyAdmin ];then
    echo -e "\033[1;37mphpMyAdmin：安装\033[0m"
    phpMyAdmin=1
else
if [[ $phpMyAdmin == 1 ]];then
    echo -e "\033[1;37mphpMyAdmin：安装\033[0m"
    phpMyAdmin=1
fi
if [[ $phpMyAdmin == 2 ]];then
    echo -e "\033[1;37mphpMyAdmin：不安装\033[0m"
    phpMyAdmin=2
fi
fi
clear;echo -n -e "\033[1;37m设置APP名称(默认:云流量):\033[0m"
read appname
if [[ -z $appname ]];then
 	appname=云流量
fi
echo -e "\033[1;37mAPP名称为：$appname\033[0m"
echo;echo -n -e "\033[1;37m设置APP客服QQ为(默认:942334458):\033[0m"
read appqq
if [[ -z $appqq ]];then
 	appqq=942334458
fi
echo -e "\033[1;37mAPP客服QQ为：$appqq\033[0m"
app_key=`curl -s http://www.qyunl.com/flowapp/getip.php?ip=${IP}`
echo;echo -n -e "\033[1;37m你是否需要导入线路到云端？1.导入 2.不导入（回车默认导入）:\033[0m"
read lineImport
if [[ -z $lineImport ]];then
    echo -e "\033[1;37m导入线路云端：导入\033[0m"
 	lineImport=1
else
if [[ $lineImport == 1 ]];then
    echo -e "\033[1;37m导入线路云端：导入\033[0m"
    lineImport=1
fi
if [[ $lineImport == 2 ]];then
    echo -e "\033[1;37m导入线路云端：不导入\033[0m"
    lineImport=2
fi
fi
fwqtype=`curl -s  http://ip138.com/ips138.asp?ip=${IP}\&action=2 | iconv -f gb2312 -t utf-8|grep '<ul class="ul1"><li>' |awk -F'[><]+' '{  
print $5}'`
if [[ $fwqtype =~ "阿里云" ]] || [[ $fwqtype =~ "腾讯云" ]] || [[ $fwqtype =~ "小鸟云" ]]; then
clear;echo -e "\033[1;31m系统检测当前为常规服务器\033[0m"
echo -e "\033[1;32m您的IP为 : ${IP}\033[0m";echo
echo -ne "\033[1;33m确认无误回车进入无人自动搭建模式";read
else
clear;echo -e "\033[1;31m检测到当前机器非常规服务器\033[0m"
echo -e "\033[1;32m您的IP为 : ${IP}\033[0m";echo
echo -ne "\033[1;33m确认无误回车进入无人自动搭建模式";read
fi
sleep 1
clear;echo -en "\033[1;34m开始整理安装环境.....\033[0m"
killall openvpn >/dev/null 2>&1
killall squid >/dev/null 2>&1
killall Proxy >/dev/null 2>&1
killall mysqld >/dev/null 2>&1
systemctl stop openvpn@server.service >/dev/null 2>&1
systemctl stop openvpn@udp53.service >/dev/null 2>&1
systemctl stop squid.service >/dev/null 2>&1
systemctl stop httpd.service >/dev/null 2>&1
systemctl stop nginx.service >/dev/null 2>&1
systemctl stop mariadb.service >/dev/null 2>&1
systemctl stop mysqld.service >/dev/null 2>&1
systemctl stop firewalld.service >/dev/null 2>&1
systemctl disable firewalld.service >/dev/null 2>&1
echo -e "\033[0;36;1m [OK]\033[0m"

echo;echo -en "\033[1;34m开始整理残留环境.....\033[0m"
qydel -rf /etc/openvpn/*
qydel -rf /etc/openvpn/
qydel -rf /etc/squid /etc/openvpn /usr/bin/vpn /usr/bin/lnmp
qydel -rf /usr/bin/Proxy /lib/systemd/system/vpn.service
qydel -rf /usr/bin/opensql /usr/bin/locksql
qydel -rf /etc/logrotate.d/php-fpm /usr/sbin/php-fpm /var/log/php-fpm /run/php-fpm /etc/sysconfig/php-fpm
qydel -rf /usr/lib64/php /usr/bin/php /usr/include/php /var/lib/php /usr/share/php 
qydel -rf /etc/init.d/nginx /usr/sbin/nginx /usr/lib64/nginx /etc/nginx/ /var/log/nginx /etc/sysconfig/nginx
qydel -rf /var/lib/mysql/*
qydel -rf /var/lib/mysql/mysql /usr/share/mysql /usr/bin/mysql /var/lib/mysql /var/lib/mysql/mysql /usr/lib64/mysql /var/lock/subsys/mysqld
qydel -rf /home/*
yum remove -y httpd >/dev/null 2>&1
yum remove -y php* >/dev/null 2>&1
$QYL_UP $QYL_VAL6 >/dev/null 2>&1
$QYL_UP $QYL_VAL10 >/dev/null 2>&1
$QYL_UP $QYL_VAL2 >/dev/null 2>&1
$QYL_UP $QYL_VAL7 >/dev/null 2>&1
$QYL_UP $QYL_VAL4 >/dev/null 2>&1
$QYL_UP $QYL_VAL9 >/dev/null 2>&1
echo -e "\033[0;36;1m [OK]\033[0m"

clear;echo -e "\033[1;34m正在更新系统源.....\033[0m"
$QYL_YUM1 >/dev/null 2>&1
$QYL_YUM2 >/dev/null 2>&1
$QYL_YUM3 >/dev/null 2>&1
if [[ $fwqtype =~ "阿里云" ]] || [[ $fwqtype =~ "腾讯云" ]] || [[ $fwqtype =~ "小鸟云" ]]; then
$QYL_IN $QYL_VAL1 >/dev/null 2>&1
$QYL_IN $QYL_VAL2 >/dev/null 2>&1
$QYL_IN $QYL_VAL5 >/dev/null 2>&1
else
yum clean all
yum makecache
yum update -y
$QYL_IN $QYL_VAL1
$QYL_IN $QYL_VAL2
$QYL_IN $QYL_VAL5
fi
echo -e "\033[1;36m更新完成\033[0m";
sleep 1

clear;echo -en "\033[1;34m正在配置网络环境.....\033[0m"
$QYL_IN $QYL_VAL3 >/dev/null 2>&1
setenforce 0 >/dev/null 2>&1
sed -i 's/SELINUX=.*/SELINUX=disabled/g' /etc/selinux/config >/dev/null 2>&1
echo "/usr/sbin/setenforce 0" >> /etc/rc.local >/dev/null 2>&1
echo -e "\033[0;36;1m [OK]\033[0m"

echo -en "\033[1;34m正在配置防火墙.....\033[0m"
systemctl start iptables >/dev/null 2>&1
systemctl restart iptables >/dev/null 2>&1
iptables -F >/dev/null 2>&1
iptables -t nat -A POSTROUTING -s 10.0.0.0/24 -o eth0 -j MASQUERADE
iptables -t nat -A POSTROUTING -s 10.0.0.0/24 -j SNAT --to-source $IP
iptables -t nat -A POSTROUTING -j MASQUERADE
iptables -t nat -A PREROUTING -p tcp -m tcp --dport 137 -j DNAT --to-destination $IP:$vpnport
iptables -t nat -A PREROUTING -p tcp -m tcp --dport 138 -j DNAT --to-destination $IP:$vpnport
iptables -t nat -A PREROUTING -p tcp -m tcp --dport 440 -j DNAT --to-destination $IP:$vpnport
iptables -t nat -A PREROUTING -p tcp -m tcp --dport 3389 -j DNAT --to-destination $IP:$vpnport
iptables -t nat -A PREROUTING -p udp -m udp --dport 3389 -j DNAT --to-destination $IP:53
iptables -A INPUT -s 127.0.0.1/32 -j ACCEPT
iptables -A INPUT -d 127.0.0.1/32 -j ACCEPT
iptables -A INPUT -p tcp --dport $vpnport -j ACCEPT
iptables -A INPUT -p tcp --dport $port -j ACCEPT
iptables -A INPUT -p tcp --dport $mpport -j ACCEPT
iptables -A INPUT -p tcp --dport $sqport -j ACCEPT
iptables -A INPUT -p tcp --dport 135 -j ACCEPT
iptables -A INPUT -p tcp --dport 136 -j ACCEPT
iptables -A INPUT -p tcp --dport 137 -j ACCEPT
iptables -A INPUT -p tcp --dport 138 -j ACCEPT
iptables -A INPUT -p tcp --dport 139 -j ACCEPT
iptables -A INPUT -p tcp --dport 180 -j ACCEPT
iptables -A INPUT -p tcp --dport 265 -j ACCEPT
iptables -A INPUT -p tcp --dport 351 -j ACCEPT
iptables -A INPUT -p tcp --dport 366 -j ACCEPT
iptables -A INPUT -p tcp --dport 440 -j ACCEPT
iptables -A INPUT -p tcp --dport 524 -j ACCEPT
iptables -A INPUT -p tcp --dport 1194 -j ACCEPT
iptables -A INPUT -p tcp --dport 3389 -j ACCEPT
iptables -A INPUT -p tcp --dport 80 -j ACCEPT
iptables -A INPUT -p tcp --dport 53 -j ACCEPT
iptables -A INPUT -p tcp --dport 22 -j ACCEPT
iptables -A INPUT -p udp --dport 53 -j ACCEPT
iptables -A INPUT -p udp --dport 3389 -j ACCEPT
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
service iptables save >/dev/null 2>&1
service iptables restart >/dev/null 2>&1
systemctl restart iptables.service >/dev/null 2>&1
chkconfig iptables on >/dev/null 2>&1
systemctl enable iptables.service >/dev/null 2>&1
setenforce 0 >/dev/null 2>&1
echo -e "\033[0;36;1m [OK]\033[0m"

echo -en "\033[1;34m正在配置网速优化...\033[0m"
cd /etc/
qydel -rf ./sysctl.conf
echo 'net.ipv4.ip_forward = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.default.accept_source_route = 0
kernel.sysrq = 0
kernel.core_uses_pid = 1
net.ipv4.tcp_syncookies = 1
net.bridge.bridge-nf-call-ip6tables = 0
net.bridge.bridge-nf-call-iptables = 0
net.bridge.bridge-nf-call-arptables = 0
kernel.msgmnb = 65536
kernel.msgmax = 65536
kernel.shmmax = 68719476736
kernel.shmall = 4294967296
net.ipv4.tcp_congestion_control= hybla
net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_keepalive_time = 1200
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_tw_recycle = 1
net.ipv4.ip_local_port_range = 1024 65000
net.ipv4.tcp_max_syn_backlog = 8192
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_syn_retries = 2
net.ipv4.tcp_tw_reuse= 1
net.inet.udp.checksum= 1
' >./sysctl.conf
chmod 0777 ./sysctl.conf
sysctl -p >/dev/null 2>&1
echo -e "\033[0;36;1m [OK]\033[0m"

echo -en "\033[1;34m正在安装主程序.....\033[0m"
$QYL_LST17 >/dev/null 2>&1
$QYL_LST2 >/dev/null 2>&1
cd /etc/openvpn/
echo "##################################
#       OpenVPN - qyun.com       #
#           2017.07.28           #
##################################
port $vpnport
proto tcp
dev tun
ca /etc/openvpn/easy-rsa/keys/ca.crt
cert /etc/openvpn/easy-rsa/keys/centos.crt
key /etc/openvpn/easy-rsa/keys/centos.key
dh /etc/openvpn/easy-rsa/keys/dh2048.pem
auth-user-pass-verify /etc/openvpn/login.sh via-env
client-disconnect /etc/openvpn/disconnect.sh
client-connect /etc/openvpn/connect.sh
client-cert-not-required
username-as-common-name
script-security 3 system
server 10.6.0.0 255.255.0.0
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 119.29.29.29"
push "dhcp-option DNS 114.114.114.114"
management localhost 7505
keepalive 10 120
tls-auth /etc/openvpn/easy-rsa/ta.key 0  
comp-lzo
persist-key
persist-tun
status /home/wwwroot/default/res/tcp.txt
log /etc/openvpn/openvpn.log
log-append /etc/openvpn/openvpn.log
verb 3" >/etc/openvpn/server.conf

echo "##################################
#       OpenVPN - qyun.com       #
#           2017.07.28           #
##################################
port 53
proto udp
dev tun
ca /etc/openvpn/easy-rsa/keys/ca.crt
cert /etc/openvpn/easy-rsa/keys/centos.crt
key /etc/openvpn/easy-rsa/keys/centos.key
dh /etc/openvpn/easy-rsa/keys/dh2048.pem
auth-user-pass-verify /etc/openvpn/login.sh via-env
client-disconnect /etc/openvpn/disconnect.sh
client-connect /etc/openvpn/connect.sh
client-cert-not-required
username-as-common-name
script-security 3 system
server 10.8.0.0 255.255.255.0
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 119.29.29.29"
push "dhcp-option DNS 114.114.114.114"
management localhost 7506
keepalive 10 120
tls-auth /etc/openvpn/easy-rsa/ta.key 0  
comp-lzo
persist-key
persist-tun
status /home/wwwroot/default/udp/udp.txt 1
log         openvpn.log
log-append  openvpn.log
verb 3" >/etc/openvpn/udp53.conf
echo -e "\033[0;36;1m [OK]\033[0m"

echo -en "\033[1;34m正在配置OpenVPN.....\033[0m"
$QYL_LST4 >/dev/null 2>&1
tar -zxvf Easy-RSA.tar.gz >/dev/null 2>&1
qydel -rf /etc/openvpn/Easy-RSA.tar.gz >/dev/null 2>&1
chmod -R 0777 /etc/openvpn/
systemctl enable openvpn@server.service >/dev/null 2>&1
cp /etc/openvpn/easy-rsa/keys/ca.crt /home/ >/dev/null 2>&1
cp /etc/openvpn/easy-rsa/ta.key /home/ >/dev/null 2>&1
echo "echo -e '\033[33m正在重启openvpn服务...\033[0m'
killall openvpn >/dev/null 2>&1
systemctl stop openvpn@server.service
systemctl stop openvpn@udp53.service
systemctl restart openvpn@server.service
systemctl restart openvpn@udp53.service
systemctl restart iptables.service
killall Proxy >/dev/null 2>&1
Proxy -l $mpport -d >/dev/null 2>&1
Proxy -l 53 -d >/dev/null 2>&1
Proxy -l 135 -d >/dev/null 2>&1
Proxy -l 136 -d >/dev/null 2>&1
Proxy -l 137 -d >/dev/null 2>&1
Proxy -l 138 -d >/dev/null 2>&1
Proxy -l 139 -d >/dev/null 2>&1
Proxy -l 180 -d >/dev/null 2>&1
Proxy -l 265 -d >/dev/null 2>&1
Proxy -l 351 -d >/dev/null 2>&1
Proxy -l 366 -d >/dev/null 2>&1
Proxy -l 440 -d >/dev/null 2>&1
Proxy -l 443 -d >/dev/null 2>&1
Proxy -l 524 -d >/dev/null 2>&1
Proxy -l 1194 -d >/dev/null 2>&1
Proxy -l 3389 -d >/dev/null 2>&1
killall squid >/dev/null 2>&1
killall squid >/dev/null 2>&1
squid -z >/dev/null 2>&1
systemctl restart squid
lnmp >/dev/null 2>&1
killall Monitor >/dev/null 2>&1
killall backups.sh >/dev/null 2>&1
/bin/Monitor "/home/wwwroot/default/res/tcp.txt" 7505 >>/home/jiankong.log 2>&1 &  >/dev/null 2>&1
/bin/Monitor "/home/wwwroot/default/udp/udp.txt" 7506 >>/home/jiankong.log 2>&1 &  >/dev/null 2>&1
/etc/openvpn/backups.sh >>/home/wwwroot/backups.log 2>&1 &
echo -e '服务状态：			  [\033[32m  OK  \033[0m]'
exit 0;
" >/bin/vpn
chmod 777 /bin/vpn
chmod +x /etc/rc.d/rc.local
echo "sh /bin/vpn" >>/etc/rc.d/rc.local
echo -e "\033[0;36;1m [OK]\033[0m"

echo -en "\033[1;34m正在安装HTTP代理端口......\033[0m"
$QYL_IN $QYL_VAL9 >/dev/null 2>&1
cd /etc/squid/
qydel -rf ./squid.conf
$QYL_LST5 >/dev/null 2>&1
sleep 0.5
sed -i 's/http_port 80/http_port '$sqport'/g' /etc/squid/squid.conf >/dev/null 2>&1
chmod 0755 ./squid.conf >/dev/null 2>&1
$QYL_LST6 >/dev/null 2>&1
chmod 0755 ./auth_user >/dev/null 2>&1
cd /etc/
chmod 777 -R squid >/dev/null 2>&1
cd squid
squid -z >/dev/null 2>&1
systemctl restart squid >/dev/null 2>&1
systemctl enable squid >/dev/null 2>&1
echo -e "\033[0;36;1m [OK]\033[0m"

echo -en "\033[1;34m正在安装HTTP转发模式......\033[0m"
cd /usr/bin/
$QYL_LST7 >/dev/null 2>&1
sed -i "23s/8080/$mpport/" Proxy.c
gcc -o Proxy Proxy.c
qydel -rf Proxy.c >/dev/null 2>&1
chmod 0777 ./Proxy >/dev/null 2>&1
echo -e "\033[0;36;1m [OK]\033[0m"

echo -en "\033[1;34m正在安装Ngixn......\033[0m"
mkdir -p /home/wwwroot/default >/dev/null 2>&1
mkdir -p /home/wwwlog/ >/dev/null 2>&1
$QYL_YUM5 >/dev/null 2>&1
$QYL_IN $QYL_VAL4 >/dev/null 2>&1
mv /usr/share/nginx /home/wwwroot >/dev/null 2>&1
qydel -rf /etc/nginx/conf.d/default.conf >/dev/null 2>&1
$QYL_LST3 >/dev/null 2>&1
chmod 777 /etc/nginx/conf.d/default.conf >/dev/null 2>&1
systemctl enable nginx.service >/dev/null 2>&1
systemctl start nginx.service >/dev/null 2>&1
echo -e "\033[0;36;1m [OK]\033[0m"

echo -en "\033[1;34m正在安装Mariadb......\033[0m"
$QYL_IN $QYL_VAL7 >/dev/null 2>&1
systemctl enable mariadb.service >/dev/null 2>&1
systemctl restart mariadb.service >/dev/null 2>&1
echo -e "\033[0;36;1m [OK]\033[0m"

echo -en "\033[1;34m正在安装PHP......\033[0m"
$QYL_IN $QYL_VAL6 >/dev/null 2>&1
sed -i 's/;date.timezone =/date.timezone = PRC/g' /etc/php.ini >/dev/null 2>&1
sed -i 's,listen = 127.0.0.1:9000,listen = /var/run/php-fpm/php5-fpm.sock,g' /etc/php-fpm.d/www.conf
sed -i 's/;listen.owner = nobody/listen.owner = nginx/g' /etc/php-fpm.d/www.conf
sed -i 's/;listen.group = nobody/listen.group = nginx/g' /etc/php-fpm.d/www.conf
sed -i 's/;listen.mode = 0660/listen.mode = 0660/g' /etc/php-fpm.d/www.conf
systemctl enable php-fpm.service >/dev/null 2>&1
systemctl start php-fpm.service >/dev/null 2>&1
echo -e "\033[0;36;1m [OK]\033[0m"

echo "#!/bin/bash
echo '正在重启lnmp...'
systemctl restart mariadb
systemctl restart nginx.service
systemctl restart php-fpm.service
systemctl restart crond.service
echo -e '服务状态：			  [\033[32m  OK  \033[0m]'
exit 0;
" >/bin/lnmp
chmod 777 /bin/lnmp >/dev/null 2>&1
lnmp >/dev/null 2>&1

echo '#!/bin/bash
echo -e "使用前请检查您的服务器端口是否全开"
echo;echo -n "请输入HTTP叠加端口:"
read oport
iptables -A INPUT -p TCP --dport ${oport} -j ACCEPT
service iptables save >/dev/null 2>&1
service iptables restart >/dev/null 2>&1
Proxy -l $oport -d
' >/bin/oport
chmod 0777 /bin/oport >/dev/null 2>&1
echo -en "\033[1;34m开始安装青云流控......\033[0m"
mysqladmin -u root password "${sqlpass}"
cd /root
$QYL_LST8 >/dev/null 2>&1
sleep 0.5
unzip qyun-web.zip >/dev/null 2>&1
chmod 777 -R /root/qyun/* >/dev/null 2>&1
sed -i 's/mysqlpass/'$sqlpass'/g' ./qyun/web/config.php >/dev/null 2>&1
sed -i 's/phpmyadmin/'$Tokey'/g' ./qyun/web/version.php >/dev/null 2>&1
passmd5=`echo -n $password|md5sum`
sed -i 's/administrator/'$username'/g' /root/qyun/web/install.sql >/dev/null 2>&1
sed -i 's/青云流控/'$appname'/g' /root/qyun/web/install.sql >/dev/null 2>&1
sed -i 's/942334458/'$appqq'/g' /root/qyun/web/install.sql >/dev/null 2>&1
sed -i 's/www.qyunl.com/'${IP}:${port}'/g' /root/qyun/web/install.sql >/dev/null 2>&1
sed -i 's/9702bec258c38676a1217f2c0c58d610/'${passmd5%%\ *}'/g' /root/qyun/web/install.sql >/dev/null 2>&1
sed -i 's/88de7b9385ffeda9a40766dcfcb8ca8b/'${apptoken}'/g' /root/qyun/web/install.sql >/dev/null 2>&1
qydel -rf /home/wwwroot/default/html/index* >/dev/null 2>&1
mv -f ./qyun/web/* /home/wwwroot/default/ >/dev/null 2>&1
chmod 777 -R /home/wwwroot/default/ >/dev/null 2>&1
create_db_sql="create database IF NOT EXISTS ov"
mysql -hlocalhost -uroot -p$sqlpass -e "${create_db_sql}"
chmod 777 /home/wwwroot/default/install.sql >/dev/null 2>&1
mysql -hlocalhost -uroot -p$sqlpass --default-character-set=utf8<<EOF
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%'IDENTIFIED BY '${sqlpass}' WITH GRANT OPTION;
flush privileges;
use ov;
source /home/wwwroot/default/install.sql;
EOF
sleep 0.5
qydel -rf /home/wwwroot/default/install.sql >/dev/null 2>&1
mv -f ./qyun/sh/login.sh /etc/openvpn/ >/dev/null 2>&1
mv -f ./qyun/sh/disconnect.sh /etc/openvpn/ >/dev/null 2>&1
mv -f ./qyun/sh/connect.sh /etc/openvpn/ >/dev/null 2>&1
mv -f ./qyun/sh/common/ /etc/openvpn/common/ >/dev/null 2>&1
chmod +x /etc/openvpn/*.sh >/dev/null 2>&1
qydel -rf /root/qyun/ >/dev/null 2>&1
qydel -rf /root/qyun-web.zip >/dev/null 2>&1
chmod 777 -R /home/wwwroot/default/* >/dev/null 2>&1
echo -e "\033[0;36;1m [OK]\033[0m"

if [[ $phpMyAdmin == 1 ]];then
echo -en "\033[1;34m正在安装网页数据库......\033[0m"
cd /home/wwwroot/default/
$QYL_LST18 >/dev/null 2>&1
tar -zxvf phpmyadmin.tar.gz >/dev/null 2>&1
qydel -rf phpmyadmin.tar.gz >/dev/null 2>&1
mv /home/wwwroot/default/phpmyadmin /home/wwwroot/default/$Tokey >/dev/null 2>&1
chmod 777 -R /home/wwwroot/default/$Tokey/* >/dev/null 2>&1
echo -e "\033[0;36;1m [OK]\033[0m"
fi

echo -en "\033[1;34m开始设置流控端口......\033[0m"
sed -i 's/80/'$port'/g' /usr/local/nginx/conf/nginx.conf >/dev/null 2>&1
sed -i 's/80/'$port'/g' /etc/nginx/conf.d/default.conf >/dev/null 2>&1
echo -e "\033[0;36;1m [OK]\033[0m"

echo -en "\033[1;34m开始安装流量监控程序......\033[0m"
mkdir -p /var/spool/cron/ >/dev/null 2>&1
chmod 777 /home/wwwroot/default/cron.php >/dev/null 2>&1
echo "* * * * * curl --silent --compressed http://${IP}:${port}/cron.php">>/var/spool/cron/root >/dev/null 2>&1
cd /usr/bin/
$QYL_LST1 >/dev/null 2>&1
$QYL_LST10 >/dev/null 2>&1
echo $(date +%Y年%m月%d日%k时%M分) 开始监控TCP用户..."</br>" >>/home/jiankong.log
echo $(date +%Y年%m月%d日%k时%M分) 开始监控UDP用户..."</br>" >>/home/jiankong.log
chmod 777 /bin/Monitor >/dev/null 2>&1
chmod 777 /bin/Monsha >/dev/null 2>&1
systemctl restart crond.service  >/dev/null 2>&1   
systemctl enable crond.service >/dev/null 2>&1 
chmod 777 -R /home/wwwroot/default/res/
chmod 777 -R /home/wwwroot/default/udp/
cd /etc/openvpn/
$QYL_LST11 >/dev/null 2>&1
sed -i 's/butime=86400/'butime=$butime'/g' /etc/openvpn/peizhi.cfg >/dev/null 2>&1
sed -i 's/mima=123456/'mima=$sqlpass'/g' /etc/openvpn/peizhi.cfg >/dev/null 2>&1
sed -i 's/webhost=www.qyunl.com/'webhost=$IP:$port'/g' /etc/openvpn/peizhi.cfg >/dev/null 2>&1
echo -e "\033[0;36;1m [OK]\033[0m"

echo -en "\033[1;34m开始安装自动备份程序......\033[0m"
$QYL_LST12 >/dev/null 2>&1
chmod 777 /etc/openvpn/backups.sh >/dev/null 2>&1
echo "/etc/openvpn/backups.sh >>/home/backups.log 2>&1 &">>/etc/rc.local >/dev/null 2>&1
echo -e "\033[0;36;1m [OK]\033[0m"

if [[ $lineImport == 1 ]];then
echo -en "\033[1;34m开始导入线路到云端......\033[0m"
cd /home
$QYL_LST19 >/dev/null 2>&1
OPENVPNCRT=`cat /etc/openvpn/easy-rsa/keys/ca.crt`;
OPENVPNKEY=`cat /etc/openvpn/easy-rsa/ta.key`;
chmod 777 /home/line.sql >/dev/null 2>&1
mysql -hlocalhost -uroot -p$sqlpass ov </home/line.sql >/dev/null 2>&1
sleep 1
mysql -hlocalhost -uroot -p$sqlpass ov -e "UPDATE line SET content = REPLACE( content,   '%IP%',  '$IP');" >/dev/null 2>&1
mysql -hlocalhost -uroot -p$sqlpass ov -e "UPDATE line SET content = REPLACE( content,   '%OPENVPNCRT%',  '$OPENVPNCRT');" >/dev/null 2>&1
mysql -hlocalhost -uroot -p$sqlpass ov -e "UPDATE line SET content = REPLACE( content,   '%OPENVPNKEY%',  '$OPENVPNKEY');" >/dev/null 2>&1
qydel -rf /home/line.sql
lnmp >/dev/null 2>&1
echo -e "\033[0;36;1m [OK]\033[0m"
fi

echo;echo -e "\033[1;32;1m开始编译青云应用......\033[0m"
echo -en "\033[1;33m"
$QYL_LST13 >/dev/null 2>&1
$QYL_LST14 >/dev/null 2>&1
if [ ! -e "/usr/bin/java" ];then
$QYL_IN $QYL_VAL8 >/dev/null 2>&1
fi
cd /home
mkdir android
chmod 777 -R /home/android
cp /home/apktool.jar /home/android/apktool.jar >/dev/null 2>&1
cd /home/android
$QYL_LST15 >/dev/null 2>&1
if [ ! -f "/home/android/apktool.jar" ]; then
	$QYL_LST13 >/dev/null 2>&1
fi
if [ ! -f "/home/android/qyun.apk" ]; then
	$QYL_LST15 >/dev/null 2>&1
fi
sleep 0.5
java -jar apktool.jar d qyun.apk
sed -i 's/www.qyunl.com/'${IP}:${port}'/g' /home/android/qyun/smali/net/openvpn/openvpn/AutoScrollTextView.smali >/dev/null 2>&1
sed -i 's/www.qyunl.com/'${IP}:${port}'/g' /home/android/qyun/smali/net/openvpn/openvpn/ChongzhiActivity.smali >/dev/null 2>&1
sed -i 's/www.qyunl.com/'${IP}:${port}'/g' '/home/android/qyun/smali/net/openvpn/openvpn/DoActivity$3.smali' >/dev/null 2>&1
sed -i 's/www.qyunl.com/'${IP}:${port}'/g' '/home/android/qyun/smali/com/mayor/prg/mst$2.smali' >/dev/null 2>&1
sed -i 's/www.qyunl.com/'${IP}:${port}'/g' /home/android/qyun/smali/net/openvpn/openvpn/MainActivity.smali >/dev/null 2>&1
sed -i 's/www.qyunl.com/'${IP}:${port}'/g' /home/android/qyun/smali/net/openvpn/openvpn/MainTabActivity.smali >/dev/null 2>&1
sed -i 's/www.qyunl.com/'${IP}:${port}'/g' /home/android/qyun/smali/net/openvpn/openvpn/OpenVPNClient.smali >/dev/null 2>&1
sed -i 's/88de7b9385ffeda9a40766dcfcb8ca8b/'$apptoken'/g' /home/android/qyun/smali/net/openvpn/openvpn/AutoScrollTextView.smali >/dev/null 2>&1
sed -i 's/88de7b9385ffeda9a40766dcfcb8ca8b/'$apptoken'/g' '/home/android/qyun/smali/com/mayor/prg/mst$2.smali' >/dev/null 2>&1
sed -i 's/88de7b9385ffeda9a40766dcfcb8ca8b/'$apptoken'/g' /home/android/qyun/smali/net/openvpn/openvpn/ChongzhiActivity.smali >/dev/null 2>&1
sed -i 's/88de7b9385ffeda9a40766dcfcb8ca8b/'$apptoken'/g' '/home/android/qyun/smali/net/openvpn/openvpn/DoActivity$3.smali' >/dev/null 2>&1
sed -i 's/88de7b9385ffeda9a40766dcfcb8ca8b/'$apptoken'/g' /home/android/qyun/smali/net/openvpn/openvpn/MainActivity.smali >/dev/null 2>&1
sed -i 's/88de7b9385ffeda9a40766dcfcb8ca8b/'$apptoken'/g' /home/android/qyun/smali/net/openvpn/openvpn/MainTabActivity.smali >/dev/null 2>&1
sed -i 's/88de7b9385ffeda9a40766dcfcb8ca8b/'$apptoken'/g' /home/android/qyun/smali/net/openvpn/openvpn/OpenVPNClient.smali >/dev/null 2>&1
sed -i 's/青云云流量/'$appname'/g' /home/android/qyun/res/values/strings.xml >/dev/null 2>&1
sed -i 's/100340768/'$appqq'/g' /home/android/qyun/res/values/strings.xml >/dev/null 2>&1
sleep 0.5
sudo chmod +x /home/android/apktool.jar
java -jar apktool.jar b qyun >/dev/null 2>&1
cp /home/signer.tar.gz /home/android/qyun/dist/ >/dev/null 2>&1
cd /home/android/qyun/dist
if [ ! -f "/home/android/qyun/dist/signer.tar.gz" ]; then
	$QYL_LST14 >/dev/null 2>&1
fi
tar zxf signer.tar.gz >/dev/null 2>&1
java -jar signapk.jar testkey.x509.pem testkey.pk8 qyun.apk qyunl.apk
\cp -rf /home/android/qyun/dist/qyunl.apk /home/qyun.apk
qydel -rf /home/android >/dev/null 2>&1
if [ ! -e "/home/qyun.apk" ];then
echo -e "\033[1;31mAPP没有生成成功。请安装完后执行脚本使用APP生成功能..\033[0m"
else
echo -e "\033[1;32;1m编译成功\033[0m"
fi


echo;echo -e "\033[1;32;1m开始生成流量卫士APP..."
echo -en "\033[1;33m"
cd /home
mkdir android
chmod 777 -R /home/android
cp /home/apktool.jar /home/android/apktool.jar >/dev/null 2>&1
cd /home/android
$QYL_LST16 >/dev/null 2>&1
if [ ! -f "/home/android/apktool.jar" ]; then
	$QYL_LST13 >/dev/null 2>&1
fi
java -jar apktool.jar d llws.apk
sed -i 's/www.qyunl.com:80/'${IP}:${port}'/g' /home/android/llws/smali/net/openvpn/openvpn/base.smali >/dev/null 2>&1
sed -i 's/APP_KEY_CODE/'$app_key'/g' /home/android/llws/smali/net/openvpn/openvpn/base.smali >/dev/null 2>&1
sed -i 's/www.qyunl.com:80/'${IP}:${port}'/g' '/home/android/llws/smali/net/openvpn/openvpn/Main2Activity$MyListener$1.smali' >/dev/null 2>&1
sed -i 's/www.qyunl.com:80/'${IP}:${port}'/g' '/home/android/llws/smali/net/openvpn/openvpn/Main2Activity$MyListener.smali' >/dev/null 2>&1
sed -i 's/www.qyunl.com:80/'${IP}:${port}'/g' /home/android/llws/smali/net/openvpn/openvpn/MainActivity.smali >/dev/null 2>&1
sed -i 's/www.qyunl.com:80/'${IP}:${port}'/g' '/home/android/llws/smali/net/openvpn/openvpn/OpenVPNClient$10.smali' >/dev/null 2>&1
sed -i 's/www.qyunl.com:80/'${IP}:${port}'/g' '/home/android/llws/smali/net/openvpn/openvpn/OpenVPNClient$11.smali' >/dev/null 2>&1
sed -i 's/www.qyunl.com:80/'${IP}:${port}'/g' '/home/android/llws/smali/net/openvpn/openvpn/OpenVPNClient$13.smali' >/dev/null 2>&1
sed -i 's/www.qyunl.com:80/'${IP}:${port}'/g' /home/android/llws/smali/net/openvpn/openvpn/OpenVPNClient.smali >/dev/null 2>&1
sed -i 's/www.qyunl.com:80/'${IP}:${port}'/g' '/home/android/llws/smali/net/openvpn/openvpn/splash$1$1.smali' >/dev/null 2>&1
sed -i 's/www.qyunl.com:80/'${IP}:${port}'/g' '/home/android/llws/smali/net/openvpn/openvpn/splash$2.smali' >/dev/null 2>&1
sed -i 's/www.qyunl.com:80/'${IP}:${port}'/g' '/home/android/llws/smali/net/openvpn/openvpn/update$myClick$1.smali' >/dev/null 2>&1
sed -i 's/青云简约清爽/'$appname'/g' /home/android/llws/res/values/strings.xml >/dev/null 2>&1
sudo chmod +x /home/android/apktool.jar
java -jar apktool.jar b llws >/dev/null 2>&1
cp /home/signer.tar.gz /home/android/llws/dist/signer.tar.gz >/dev/null 2>&1
cd /home/android/llws/dist
if [ ! -f "/home/android/llws/dist/signer.tar.gz" ]; then
    $QYL_LST14 >/dev/null 2>&1
fi
tar zxf signer.tar.gz >/dev/null 2>&1
java -jar signapk.jar testkey.x509.pem testkey.pk8 llws.apk llwsapp.apk
\cp -rf /home/android/llws/dist/llwsapp.apk /home/llws.apk
if [ ! -e "/home/llws.apk" ];then
echo -e "\033[1;31mAPP没有生成成功。请安装完后执行脚本使用APP生成功能..\033[0m"
else
echo -e "\033[1;32;1m编译成功\033[0m"
fi
cd /home
zip qyun-openvpn.zip ./{llws.apk,qyun.apk,ca.crt,ta.key} >/dev/null 2>&1
qydel -rf llws >/dev/null 2>&1
qydel -rf android >/dev/null 2>&1
qydel -rf /home/apktool.jar >/dev/null 2>&1
qydel -rf /home/signer.tar.gz >/dev/null 2>&1
qydel -rf /root/ShakaApktool >/dev/null 2>&1
echo
echo -e "\033[1;36m欢迎使用《青云OpenVPN快速安装脚本》\033[0m" >>info.txt
echo -e "\033[1;37m
---------------------------------------------------------
小白免流官网   http://xbml.vip/
小白QQ         1475129762
前台/用户中心：http://${IP}:${port}
后台管理系统： http://${IP}:${port}/admin
代理中心：     http://${IP}:${port}/daili
数据库后台：   http://${IP}:${port}/${Tokey}
IOS线路下载：  http://${IP}:${port}/user/ios.php
---------------------------------------------------------

---------------------------------------------------------
您的数据库用户名：root 数据库密码：${sqlpass}
后台管理员用户名：${username} 管理密码：${password}
APP加固地址：http://jaq.alibaba.com/
重启命令：vpn 重启web命令：lnmp 开端口命令：oport
---------------------------------------------------------

---------------------------------------------------------
流控系统根目录:/home/wwwroot/default/
前台引导页目录:/home/wwwroot/default/web/
前台用户中心目录:/home/wwwroot/default/user/
流控后台线路证书目录:/home/wwwroot/default/open/
---------------------------------------------------------

\033[0m">>info.txt
clear;echo -e "\033[1;35m正在为您开启所有服务...\033[0m"
vpn >/dev/null 2>&1
clear
echo -e "\033[1;34m进配置文件已经上传完毕！正在加载您的配置信息...\033[0m"
cat info.txt
echo -e "\033[1;37mAPP下载链接：http://${IP}:${port}/qyun-openvpn.zip\033[0m"
\cp -rf /home/qyun-openvpn.zip /home/wwwroot/default/qyun-openvpn.zip
echo
echo -e "\033[1;31m您的IP是：$IP （如果与您实际IP不符合或空白，请自行修改.ovpn配置）\033[0m"
chattr -i /etc/hosts >/dev/null 2>&1
mv /etc/hosts  /etc/hosts1
echo "127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
123.207.218.169 sq.qyunl.com
123.207.218.169 www.qyunl.com" >/etc/hosts
chattr +i /etc/hosts >/dev/null 2>&1
exit 0;
fi
if [[ $installslect == "2" ]];then
read has < <(cat /home/wwwroot/default/version.php | grep "'7.6'")
clear;echo -e "\033[1;35m升级程序加载中...\033[0m"
if [ -n "$has" ];then
clear;echo -e "\033[1;35m开始整理系统文件...\033[0m"
if test -f  /usr/bin/qydel;then
del=qydel
else
del=rm
fi
$del -rf /home/wwwroot/default/open/appland.php >/dev/null 2>&1
$del -rf /home/wwwroot/default/open/appoff.php >/dev/null 2>&1
$del -rf /home/wwwroot/default/version.php >/dev/null 2>&1
$del -rf /etc/openvpn/login.sh >/dev/null 2>&1
$del -rf /etc/openvpn/disconnect.sh >/dev/null 2>&1
sleep 1
echo;echo -e "\033[1;36m开始下载更新程序...\033[0m"
cd /etc/openvpn
wget http://qyunl.com/update.zip >/dev/null 2>&1
unzip update.zip
sed -i 's/phpmyadmin/'$Tokey'/g' /etc/openvpn/version.php >/dev/null 2>&1
$del -rf update.zip >/dev/null 2>&1
sleep 1
echo;echo -e "\033[1;36m修复流控链接断开账户防注入过滤...\033[0m"
chmod 777 -R /etc/openvpn/*
mv -f /etc/openvpn/version.php /home/wwwroot/default/version.php >/dev/null 2>&1
chmod 777 -R /home/wwwroot/default/*
sleep 1
echo;echo -e "\033[1;36m修复完毕，开始为您重启openvpn...\033[0m"
vpn
exit;
else
clear;echo -e "\033[1;35m温馨提示：程序检测到您的流控版本无法使用此更新功能\033[0m"
echo -e "\033[1;33m本次更新只适用于7.6版本升级7.6.1版本！\033[0m"
exit;
fi
fi
if [[ $installslect == "3" ]];then
clear;echo -e "\033[1;35m温馨提示：对此操作未了解其意义的请勿继续操作！\033[0m"
echo -e "\033[1;33m管理对接需要在两台服务器执行以下对应选项\033[0m"
echo;echo -e "\033[1;37m请选择主机类型：\033[0m"
echo
echo -e "\033[1;32m 1 - 本机为主服务器（开启本机管理系统）\033[0m" 
echo -e "\033[1;32m 2 - 本机为次服务器（接入到管理服务器）\033[0m"
echo
echo -n -e  "\033[1;37m输入选项: "
read docked
case $docked in
[1]|[1-2]) ;;
*) echo -e '\n ...选择错误，安装被终止';exit 0 ;;
esac
if [[ "$docked" == "1" ]];then
if test -f  /etc/openvpn/peizhi.cfg;then
source /etc/openvpn/peizhi.cfg
else
echo -e "\033[1;31m亲，配置文件不存在，请检测是本机否搭建青云流控\033[0m" ;exit 0;
fi
clear;echo -e "\033[1;35m程序正在为您读取数据中...\033[0m"
sleep 1
clear;echo -e "\033[1;37m>您的IP为：${IP}\033[0m"
echo -e "\033[1;37m>数据库账号为：${root}\033[0m"
echo -e "\033[1;37m>数据库密码为：${mima}\033[0m"
echo
echo -e -n "\033[1;37m>以上信息没有错误，请点击回车键继续 \033[0m"
read peizhi
echo;echo -e "\033[1;32m即将开始下一步...\033[0m"
echo ">>>>>>>>>>"
clear;echo -e "\033[1;37m在开启主服务器远程数据库功能...\033[0m"
mysql -h$localhost -u$root -p$mima --default-character-set=utf8<<EOF
GRANT ALL PRIVILEGES ON *.* TO '${root}'@'%'IDENTIFIED BY '${mima}' WITH GRANT OPTION;
flush privileges;
EOF
echo -e "\033[0;36;1m [OK]\033[0m"
echo;echo -e "\033[1;37m在开启3306远程端口...\033[0m"
/sbin/iptables -I INPUT -p tcp --dport 3306 -j ACCEPT >/dev/null 2>&1
echo -e "\033[0;36;1m [OK]\033[0m"
echo;echo -e "\033[1;37m开始重启VPN服务...\033[0m"
vpn >/dev/null 2>&1
echo -e "\033[0;36;1m [OK]\033[0m"
echo;echo -e " 主服务器配置完成  [  \033[32mOK\033[0m  ]";exit 0
fi
if [[ "$docked" == "2" ]];then
if test -f  /etc/openvpn/peizhi.cfg;then
source /etc/openvpn/peizhi.cfg
else
echo -e "\033[31m亲，配置文件不存在，请检测是本机否搭建青云流控\033[0m" ;exit 0;
fi
clear;echo -e "\033[1;37m正在进入对接主机向导...\033[0m"
echo;echo -n -e "\033[1;37m请输入主服务器IP(远程数据库域名或IP,不带http://):\033[0m"
read ADMINIP
if [[ $ADMINIP == "" ]];then
echo;echo -n -e "\033[1;37m主服务器IP不能为空，请重新执行脚本对接！\033[0m";exit 0
else
echo -e "\033[1;37m您输入的主服务器IP为：$ADMINIP\033[0m"
fi
echo;echo -n -e "\033[1;37m请输入主服务器数据库账号(默认：root):\033[0m"
read mysqlroot
if [[ -z $mysqlroot ]];then
 	mysqlroot=root
fi
echo -e "\033[1;37m主服务器数据库账号为：$mysqlroot\033[0m"
echo;echo -n -e "\033[1;37m请输入主服务器数据库密码(默认：root):\033[0m"
read mysqlpass
if [[ -z $mysqlpass ]];then
 	mysqlpass=root
fi
echo -e "\033[1;37m主服务器数据库密码为：$mysqlpass\033[0m"
echo;echo -e -n "\033[1;37m>以上信息没有错误，请点击回车键继续 \033[0m"
read peizhi
echo;echo -e "\033[1;32m即将开始下一步...\033[0m"
echo ">>>>>>>>>>"
echo "#流控地址
webhost=$webhost;
#设置自动备份时间
butime==$butime;
#数据库地址
localhost=$ADMINIP;
#数据库账号
root=$mysqlroot;
#数据库密码
mima=$mysqlpass;
" >/home/peizhi.cfg
qydel -rf /etc/openvpn/peizhi.cfg >/dev/null 2>&1
mv /home/peizhi.cfg /etc/openvpn/peizhi.cfg >/dev/null 2>&1
chmod 777 /etc/openvpn/peizhi.cfg
qydel -rf /home/wwwroot/default/config.php
wget -O /home/wwwroot/default/config.php http://qyunl.com/api/app_api/config.php >/dev/null 2>&1
chmod 777 /home/wwwroot/default/config.php
sed -i 's/localhost/'$ADMINIP'/g' /home/wwwroot/default/config.php >/dev/null 2>&1
sed -i 's/mysqlroot/'$mysqlroot'/g' /home/wwwroot/default/config.php >/dev/null 2>&1
sed -i 's/mysqlpass/'$mysqlpass'/g' /home/wwwroot/default/config.php >/dev/null 2>&1
echo -e " 对接成功   [  \033[32mOK\033[0m  ]"
echo -e " 请确认服务器 \033[32m $ADMINIP \033[0m 已开启管理功能"
fi
fi
if [[ $installslect == "4" ]];then
echo -e "\033[1;31m生成程序正在加载中，请稍后......\033[0m"
sleep 3
clear;echo -n -e "\033[1;37m请输入您的IP或者域名(默认为"$IP"):\033[0m"
read domain
if [[ -z $domain ]];then
 	domain=$IP
fi
echo -e "\033[1;37m输入您输入的IP或者域名为：$domain\033[0m"
echo;echo -n -e "\033[1;37m请输入您的Web流控端口(默认1234):\033[0m"
read port
if [[ -z $port ]];then
 	port=1234
fi
echo -e "\033[1;37m您输入的Web流控端口：$port\033[0m"
echo;echo -n -e "\033[1;37m设置APP名称(默认:云流量):\033[0m"
read appname
if [[ -z $appname ]];then
 	appname=云流量
fi
echo -e "\033[1;37mAPP名称为：$appname\033[0m"
echo;echo -n -e "\033[1;37m设置APP客服QQ为(默认:1475129762):\033[0m"
read appqq
if [[ -z $appqq ]];then
 	appqq=1475129762
fi
echo;echo -e "\033[1;37mAPP客服QQ为：$appqq\033[0m"
echo;echo -e "\033[1;31m授权系统正在验证服务器中...\033[0m"
app_key=`curl -s http://www.qyunl.com/flowapp/getip.php?ip=${domain}`
if [[ ${#app_key} -ne 32 ]];then
clear;echo -e "\033[1;36m您输入的域名或IP未经授权无法使用...\033[0m";exit 0
fi
echo;echo -e "\033[1;33m授权验证成功，开始安装生成所需的必要文件..."
qydel -rf /home/android >/dev/null 2>&1
cd /home
mkdir android
chmod 777 -R /home/android
$QYL_LST13 >/dev/null 2>&1
$QYL_LST14 >/dev/null 2>&1
if [ ! -e "/usr/bin/java" ];then
$QYL_IN $QYL_VAL8 >/dev/null 2>&1
fi
cp /home/apktool.jar /home/android/apktool.jar >/dev/null 2>&1
cd /home/android
if [ ! -f "/home/android/apktool.jar" ]; then
	$QYL_LST13 >/dev/null 2>&1
fi
appfile=`echo -n "${IP}_$RANDOM_$(date)" | md5sum | sed "s/ .*//" | cut -b -12`
clear;echo -e "\033[1;33m安装成功成功，请选择您要生成的美化APP："
echo -e "\033[1;37m浏览查看模板样式：http://bbs.qyunl.com/forum.php?mod=viewthread&tid=1"
echo 
echo -e "\033[1;35m 1 - 流量卫士旗舰版 \033[0m"
echo -e "\033[1;32m 2 - 青云磨砂版 \033[0m"
echo -e "\033[1;37m 3 - 青云转动源 \033[0m"
echo -e "\033[1;32m 4 - 青云黑色风暴 \033[0m"
echo -e "\033[1;35m 5 - 青云蓝色大海 \033[0m"
echo -e "\033[1;34m 6 - 青云简约清爽 \033[0m"
echo
echo -n "输入选项(不能为空): "
read appread
echo
if [[ $appread == "1" ]] || [[ -z $appread ]] ;then
apptitle=流量卫士旗舰版
echo;echo -e "\033[1;32;1m开始编译$apptitle......\033[0m"
$QYL_APP/1.apk >/dev/null 2>&1
if [ ! -f "/home/android/qyun.apk" ]; then
	$QYL_APP/1.apk >/dev/null 2>&1
fi
fi

if [[ $appread == "2" ]] ;then
apptitle=青云磨砂版
echo;echo -e "\033[1;32;1m开始编译$apptitle......\033[0m"
$QYL_APP/2.apk >/dev/null 2>&1
if [ ! -f "/home/android/qyun.apk" ]; then
	$QYL_APP/2.apk >/dev/null 2>&1
fi
fi

if [[ $appread == "3" ]] ;then
apptitle=青云转动源
echo;echo -e "\033[1;32;1m开始编译$apptitle......\033[0m"
$QYL_APP/3.apk >/dev/null 2>&1
if [ ! -f "/home/android/qyun.apk" ]; then
	$QYL_APP/3.apk >/dev/null 2>&1
fi
fi

if [[ $appread == "4" ]] ;then
apptitle=青云黑色风暴
echo;echo -e "\033[1;32;1m开始编译$apptitle......\033[0m"
$QYL_APP/4.apk >/dev/null 2>&1
if [ ! -f "/home/android/qyun.apk" ]; then
	$QYL_APP/4.apk >/dev/null 2>&1
fi
fi

if [[ $appread == "5" ]] ;then
apptitle=青云蓝色大海
echo;echo -e "\033[1;32;1m开始编译$apptitle......\033[0m"
$QYL_APP/5.apk >/dev/null 2>&1
if [ ! -f "/home/android/qyun.apk" ]; then
	$QYL_APP/5.apk >/dev/null 2>&1
fi
fi

if [[ $appread == "6" ]] ;then
apptitle=青云简约清爽
echo;echo -e "\033[1;32;1m开始编译$apptitle......\033[0m"
$QYL_APP/6.apk >/dev/null 2>&1
if [ ! -f "/home/android/qyun.apk" ]; then
	$QYL_APP/6.apk >/dev/null 2>&1
fi
fi
echo -en "\033[1;33m"
java -jar apktool.jar d qyun.apk
sed -i 's/www.qyunl.com:80/'${domain}:${port}'/g' /home/android/qyun/smali/net/openvpn/openvpn/AutoScrollTextView1.smali >/dev/null 2>&1
sed -i 's/www.qyunl.com:80/'${domain}:${port}'/g' /home/android/qyun/smali/net/openvpn/openvpn/AutoScrollTextView.smali >/dev/null 2>&1
sed -i 's/www.qyunl.com:80/'${domain}:${port}'/g' /home/android/qyun/smali/net/openvpn/openvpn/base.smali >/dev/null 2>&1
sed -i 's/APP_KEY_CODE/'${app_key}'/g' /home/android/qyun/smali/net/openvpn/openvpn/base.smali >/dev/null 2>&1
sed -i 's/www.qyunl.com:80/'${domain}:${port}'/g' "/home/android/qyun/smali/net/openvpn/openvpn/OpenVPNClient.smali" >/dev/null 2>&1
sed -i 's/www.qyunl.com:80/'${domain}:${port}'/g' "/home/android/qyun/smali/net/openvpn/openvpn/OpenVPNClient\$10.smali" >/dev/null 2>&1
sed -i 's/www.qyunl.com:80/'${domain}:${port}'/g' "/home/android/qyun/smali/net/openvpn/openvpn/OpenVPNClient\$11.smali" >/dev/null 2>&1
sed -i 's/www.qyunl.com:80/'${domain}:${port}'/g' "/home/android/qyun/smali/net/openvpn/openvpn/OpenVPNClient\$13.smali" >/dev/null 2>&1
sed -i 's/www.qyunl.com:80/'${domain}:${port}'/g' "/home/android/qyun/smali/net/openvpn/openvpn/Main2Activity\$MyListener\$1.smali" >/dev/null 2>&1
sed -i 's/www.qyunl.com:80/'${domain}:${port}'/g' '/home/android/qyun/smali/net/openvpn/openvpn/Main2Activity$MyListener.smali' >/dev/null 2>&1
sed -i 's/www.qyunl.com:80/'${domain}:${port}'/g' '/home/android/qyun/smali/net/openvpn/openvpn/MainActivity.smali' >/dev/null 2>&1
sed -i 's/www.qyunl.com:80/'${domain}:${port}'/g' '/home/android/qyun/smali/net/openvpn/openvpn/update$myClick$1.smali' >/dev/null 2>&1
sed -i 's/'${apptitle}'/'${app_name}'/g' "/home/android/qyun/res/values/strings.xml" >/dev/null 2>&1
sudo chmod +x /home/android/apktool.jar
java -jar apktool.jar b qyun >/dev/null 2>&1
cp /home/signer.tar.gz /home/android/qyun/dist/signer.tar.gz >/dev/null 2>&1
cd /home/android/qyun/dist
if [ ! -f "/home/android/qyun/dist/signer.tar.gz" ]; then
    $QYL_LST14 >/dev/null 2>&1
fi
tar zxf signer.tar.gz >/dev/null 2>&1
java -jar signapk.jar testkey.x509.pem testkey.pk8 qyun.apk /home/wwwroot/default/$appfile.apk
if [ ! -e "/home/wwwroot/default/$appfile.apk" ];then
echo;echo -e "\033[1;31mAPP没有生成成功。请安装完后执行脚本使用APP生成功能..\033[0m"
qydel -rf /home/apktool.jar >/dev/null 2>&1
qydel -rf /home/signer.tar.gz >/dev/null 2>&1
qydel -rf /root/ShakaApktool >/dev/null 2>&1
qydel -rf /home/android >/dev/null 2>&1
exit;
else
echo;echo -e "\033[1;32;1m编译成功,APP下载链接：http://$domain:$port/$appfile.apk \033[0m"
fi
qydel -rf /home/apktool.jar >/dev/null 2>&1
qydel -rf /home/signer.tar.gz >/dev/null 2>&1
qydel -rf /root/ShakaApktool >/dev/null 2>&1
qydel -rf /home/android >/dev/null 2>&1
exit;
fi
if [[ $installslect == "5" ]];then
clear;echo;echo -e "\033[1;37m您确定要卸载？请按回车开始卸载....\033[0m"
read
echo;echo -en "\033[1;34m开始关闭关联服务器应用.....\033[0m"
killall openvpn >/dev/null 2>&1
killall squid >/dev/null 2>&1
killall Proxy >/dev/null 2>&1
systemctl stop openvpn@server.service >/dev/null 2>&1
systemctl stop openvpn@udp53.service >/dev/null 2>&1
systemctl stop squid.service >/dev/null 2>&1
systemctl stop httpd.service >/dev/null 2>&1
systemctl stop nginx.service >/dev/null 2>&1
systemctl stop mariadb.service >/dev/null 2>&1
systemctl stop mysqld.service >/dev/null 2>&1
systemctl stop firewalld.service >/dev/null 2>&1
systemctl disable firewalld.service >/dev/null 2>&1
echo -e "\033[0;36;1m [OK]\033[0m"
echo;echo -en "\033[1;34m开始卸载残留环境.....\033[0m"
qydel -rf /etc/openvpn/* /etc/nginx/ /bin/lnmp /bin/vpn /etc/sysctl.conf
qydel -rf /etc/squid /etc/openvpn /usr/bin/Proxy /home/* /lib/systemd/system/vpn.service /bin/vpn
qydel -rf /home/* /usr/bin/opensql /usr/bin/locksql /usr/local/nginx /usr/local/php /usr/local/mysql
yum remove -y httpd >/dev/null 2>&1
yum remove -y php* >/dev/null 2>&1
$QYL_UP $QYL_VAL6 >/dev/null 2>&1
$QYL_UP $QYL_VAL10 >/dev/null 2>&1
$QYL_UP $QYL_VAL2 >/dev/null 2>&1
$QYL_UP $QYL_VAL7 >/dev/null 2>&1
$QYL_UP $QYL_VAL4 >/dev/null 2>&1
$QYL_UP $QYL_VAL9 >/dev/null 2>&1
echo -e "\033[0;36;1m [OK]\033[0m"
echo;echo -en "\033[1;37m卸载成功，离别是从逢的开始，现在的分别是为了下一次的相见.....\033[0m"
fi
##############################################################################################
#www.qyunl.com