#!/bin/bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH
clear
rm -rf ZSQ
# Logo	******************************************************************
CopyrightLogo='
\033[36m
==============================================================
                 欢迎使用小羽注射器脚本 				  
                 年少不轻狂、枉为少年郎
                  QQ交流群 600573662
                   Powered 小羽 2017  	
                  All Rights Reserved  
                                  By:小羽  
==============================================================\033[0m';
echo -e "$CopyrightLogo";
echo
while true
do
echo -e "设置squid代理端口 [1-65535]:"
read -p "(回车默认设置端口为: 8080):" PORT
[ -z "$PORT" ] && PORT="8080"
expr $PORT + 0 &>/dev/null
if [ $? -eq 0 ]; then
    if [ $PORT -ge 1 ] && [ $PORT -le 65535 ]; then
        echo
        echo "---------------------------"
        echo "Ok，squid端口已设置为 = $PORT"
        echo "---------------------------"
        echo
        break
     else
        echo "错误：请正确设置端口为1-65535之间的数字"
    fi
else
        echo "错误：请正确设置端口为1-65535之间的数字"
fi
done
echo -e "设置SQUID用户,建议6位数以上:"
read -p "(回车默认设置用户为: xiaoyu):" USER
[ -z "$USER" ] && USER="xiaoyu"
echo
echo "---------------------------------------"
echo "Ok，SSQUID用户 = $USER"
echo "---------------------------------------"
echo "回车确认开始安装环境...（耐心等几秒）"
read
yum install squid httpd -y >/dev/null 2>&1
service squid stop>/dev/null 2>&1
rm -f /etc/squid/squid.conf*>/dev/null 2>&1
rm -f /etc/squid/squid_passwd*>/dev/null 2>&1
echo -e "\033[33m==========================\033[0m"
echo -e "\033[0;1;35m    1.7.X系统文件     \033[0m"                
echo  
echo -e "\033[0;1;35m    2.6.X系统文件     \033[0m"
echo -e "\033[33m==========================\033[0m"
echo
echo -n "输入您要搭建的选项: " 
read mode
if [[ $mode == "1" ]]     
then
echo -e "安装类型：\033[36m7.X系统\033[0m" ;  
wget -O squid.conf https://github.com/CxiaoyuN/xiaoyu/raw/master/squid-centos7.conf >/dev/null 2>&1
fi

if [[ $mode == "2" ]]     
then
echo -e "安装类型：\033[36m6.X系统\033[0m" ;  
wget -O squid.conf https://github.com/CxiaoyuN/xiaoyu/raw/master/squid-centos6.conf >/dev/null 2>&1
fi
mv /root/squid.conf /etc/squid/squid.conf
rm -rf /root/squid.conf
cd /etc/squid/
sed -i "s/^http_port.*/http_port $PORT/g" squid.conf >/dev/null 2>&1
sed 's/xiaoyu/$USER/g' squid.conf
chmod 0755 squid.conf
MYIP=`wget http://members.3322.org/dyndns/getip -O - -q ; echo`; >/dev/null 2>&1
echo "提示new passwrod,请输入SQUID密码"
echo "提示re-type new password 再次输入SQUID密码"
htpasswd -c /etc/squid/squid_password $USER 
echo "开启路由转发..."
sleep 3
sed -i "s/^net.ipv4.ip_forward =.*/net.ipv4.ip_forward = 1/g" /etc/sysctl.conf >/dev/null 2>&1
echo "squid初始化..."
squid -z >/dev/null 2>&1
chkconfig squid on
echo "设置防火墙..."
yum install iptables -y >/dev/null 2>&1
service iptables start >/dev/null 2>&1
chkconfig iptables on
service squid start
iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport $PORT -j ACCEPT >/dev/null 2>&1
/etc/init.d/iptables save >/dev/null 2>&1
/etc/init.d/iptables restart >/dev/null 2>&1
service squid start >/dev/null 2>&1
echo "恭喜squid搭建完成"
echo "你的ip是 $MYIP ,端口$PORT(注意映射端口)"
exit 0;